
enum Tile {
    acid_refined_concrete, // = 'acid-refined-concrete',
    black_refined_concrete, // = 'black-refined-concrete',
    blue_refined_concrete, // = 'blue-refined-concrete',
    brown_refined_concrete, // = 'brown-refined-concrete',
    concrete, // = 'concrete',
    cyan_refined_concrete, // = 'cyan-refined-concrete',
    deepwater, // = 'deepwater',
    deepwater_green, // = 'deepwater-green',
    dirt_1, // = 'dirt-1',
    dirt_2, // = 'dirt-2',
    dirt_3, // = 'dirt-3',
    dirt_4, // = 'dirt-4',
    dirt_5, // = 'dirt-5',
    dirt_6, // = 'dirt-6',
    dirt_7, // = 'dirt-7',
    dry_dirt, // = 'dry-dirt',
    grass_1, // = 'grass-1',
    grass_2, // = 'grass-2',
    grass_3, // = 'grass-3',
    grass_4, // = 'grass-4',
    green_refined_concrete, // = 'green-refined-concrete',
    hazard_concrete_left, // = 'hazard-concrete-left',
    hazard_concrete_right, // = 'hazard-concrete-right',
    lab_dark_1, // = 'lab-dark-1',
    lab_dark_2, // = 'lab-dark-2',
    lab_white, // = 'lab-white',
    landfill, // = 'landfill',
    orange_refined_concrete, // = 'orange-refined-concrete',
    out_of_map, // = 'out-of-map',
    pink_refined_concrete, // = 'pink-refined-concrete',
    purple_refined_concrete, // = 'purple-refined-concrete',
    red_desert_0, // = 'red-desert-0',
    red_desert_1, // = 'red-desert-1',
    red_desert_2, // = 'red-desert-2',
    red_desert_3, // = 'red-desert-3',
    red_refined_concrete, // = 'red-refined-concrete',
    refined_concrete, // = 'refined-concrete',
    refined_hazard_concrete_left, // = 'refined-hazard-concrete-left',
    refined_hazard_concrete_right, // = 'refined-hazard-concrete-right',
    sand_1, // = 'sand-1',
    sand_2, // = 'sand-2',
    sand_3, // = 'sand-3',
    stone_path, // = 'stone-path',
    tutorial_grid, // = 'tutorial-grid',
    water, // = 'water',
    water_green, // = 'water-green',
    water_mud, // = 'water-mud',
    water_shallow, // = 'water-shallow',
    yellow_refined_concrete, // = 'yellow-refined-concrete',
}

export default Tile;
