namespace FNO.EventStream
{
    public static class KafkaTopics
    {
        /// <summary>
        /// All determistic events (+ transactions)
        /// </summary>
        public static string EVENTS => "factorino_events";

        /// <summary>
        /// Global chat, consumed by all factories
        /// </summary>
        // public static string GLOBAL_CHAT = "global_chat";

        /// <summary>
        /// Events generated by players actions on servers
        /// </summary>
        // public static string FACTORY_ACTIVITY = "factory_activity";

        /// <summary>
        /// Log output from servers
        /// </summary>
        public static string FACTORY_LOGS => "factory_logs";

        /// <summary>
        /// Not events; requests for things to happen
        /// </summary>
        public static string JOB_REQUESTS => "job_requests";
    }
}
