version: '3.5'

services:
  factorino_broker:
    image: factorino/broker
    build:
      dockerfile: src/FNO.Broker/Dockerfile
      context: .
    networks:
      - factorino
    restart: unless-stopped
  # The factory pod only needs to be built, it shouldn't be deployed
  # factorino_factory_pod:
  #   image: factorino/factory-pod
  #   build:
  #     dockerfile: src/FNO.FactoryPod/Dockerfile
  #     context: .
  factorino_readmodel:
    image: factorino/readmodel
    build:
      dockerfile: src/FNO.ReadModel/Dockerfile
      context: .
    networks:
      - factorino
    restart: unless-stopped
  factorino_orchestrator:
    image: factorino/orchestrator
    build:
      dockerfile: src/FNO.Orchestrator/Dockerfile
      context: .
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    networks:
      - factorino
    restart: unless-stopped
  factorino_webapp:
    image: factorino/webapp
    build:
      dockerfile: src/FNO.WebApp/Dockerfile
      context: .
    networks:
      - factorino
    restart: unless-stopped
    ports:
      - "5000:5000"

networks:
  factorino:
    driver: bridge
    name: factorino

volumes:
    postgres:
    pgadmin:
    