version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1-sdk
        environment:
          sonarcloud_token: sonarcloud_token
    steps:
      - checkout
      - run:
          name: Install java
          command: apt-get update && apt-get -yq install openjdk-8-jre
      - run:
          name: Install node
          command: > 
            apt-get install curl gnupg -yq
            && curl -sL https://deb.nodesource.com/setup_8.x | bash
            && apt-get install nodejs -yq
      - run:
          name: Add dotnet tool to path
          command: export PATH="${PATH}:/root/.dotnet/tools"
      - run:
          name: Install tools
          command: dotnet tool install --global dotnet-sonarscanner
      - run:
          name: Init SonarQube analysis
          command: >
            dotnet sonarscanner begin 
            /k:"TobbenTM_Factorino" 
            /o:"tobbentm-github" 
            /d:sonar.host.url="https://sonarcloud.io" 
            /d:sonar.login="$sonarcloud_token" 
            /d:sonar.language="cs" 
            /d:sonar.exclusions="**/bin/**/*,**/obj/**/*,**/vendor/**/*,**/dist/**/*,**/node_modules/**/*" 
            /d:sonar.coverage.exclusions="test/**" 
            /d:sonar.sourceEncoding="UTF-8" 
            /d:sonar.cs.opencover.reportsPath="/app/coverage/coverage.opencover.xml"
      - run:
          name: Restore nuget packages
          command: dotnet restore
      - run:
          name: Build solution
          command: dotnet build
      - run:
          name: Test solution
          command: bash test.sh
      - run:
          name: Finish SonarQube analysis
          command: dotnet sonarscanner end /d:sonar.login="$sonarcloud_token"
