# ------------------------------------------------------------------------------
# Factorino:
# ------------------------------------------------------------------------------

global:
  factorino:
    hostUrl: "https://factori.no"

factorino:
  enabled: false


# ------------------------------------------------------------------------------
# Kafka/Zookeeper:
# ------------------------------------------------------------------------------

kafka:
  enabled: true
  replicas: 1
  configurationOverrides:
    "offsets.topic.replication.factor": 1
  topics:
    - name: factorino_events
      config: "retention.ms=-1,retention.bytes=-1"
      partitions: 1
      replicationFactor: 1
    - name: global_chat
      config: "retention.ms=-1,retention.bytes=-1"
      partitions: 1
      replicationFactor: 1
    - name: factory_activity
      config: "retention.ms=-1,retention.bytes=-1"
      partitions: 1
      replicationFactor: 1
    - name: factory_logs
      config: "retention.ms=-1,retention.bytes=-1"
      partitions: 1
      replicationFactor: 1
    - name: job_requests
      config: "retention.ms=-1,retention.bytes=-1"
      partitions: 1
      replicationFactor: 1
  zookeeper:
    replicaCount: 1

# ------------------------------------------------------------------------------
# PostgreSQL:
# ------------------------------------------------------------------------------

postgresql:
  enabled: true
