version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "factorino_events:1:1:delete,global_chat:1:1:delete,factory_activity:1:1:delete,factory_logs:1:1:delete,job_requests:1:1:delete"
      KAFKA_LOG_RETENTION_MS: -1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
