using FNO.Domain.Models;

namespace FNO.Domain.Seed
{
    public static class EntityLibrary
    {
        public static FactorioEntity[] Data()
        {
            return new[]
            {
                new FactorioEntity {
                    Type = "ammo",
                    Name = "explosive-rocket",
                    Icon = "graphics/icons/explosive-rocket.png",
                    StackSize = 200,
                    Subgroup = "ammo",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "ammo",
                    Name = "explosive-uranium-cannon-shell",
                    Icon = "graphics/icons/explosive-uranium-cannon-shell.png",
                    StackSize = 200,
                    Subgroup = "ammo",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "ammo",
                    Name = "artillery-shell",
                    Icon = "graphics/icons/artillery-shell.png",
                    StackSize = 1,
                    Subgroup = "ammo",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "ammo",
                    Name = "piercing-rounds-magazine",
                    Icon = "graphics/icons/piercing-rounds-magazine.png",
                    StackSize = 200,
                    Subgroup = "ammo",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "ammo",
                    Name = "atomic-bomb",
                    Icon = "graphics/icons/atomic-bomb.png",
                    StackSize = 10,
                    Subgroup = "ammo",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "ammo",
                    Name = "rocket",
                    Icon = "graphics/icons/rocket.png",
                    StackSize = 200,
                    Subgroup = "ammo",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "ammo",
                    Name = "firearm-magazine",
                    Icon = "graphics/icons/firearm-magazine.png",
                    StackSize = 200,
                    Subgroup = "ammo",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "ammo",
                    Name = "explosive-cannon-shell",
                    Icon = "graphics/icons/explosive-cannon-shell.png",
                    StackSize = 200,
                    Subgroup = "ammo",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "ammo",
                    Name = "uranium-cannon-shell",
                    Icon = "graphics/icons/uranium-cannon-shell.png",
                    StackSize = 200,
                    Subgroup = "ammo",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "ammo",
                    Name = "shotgun-shell",
                    Icon = "graphics/icons/shotgun-shell.png",
                    StackSize = 200,
                    Subgroup = "ammo",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "ammo",
                    Name = "railgun-dart",
                    Icon = "graphics/icons/railgun-ammo.png",
                    StackSize = 200,
                    Subgroup = "ammo",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "ammo",
                    Name = "piercing-shotgun-shell",
                    Icon = "graphics/icons/piercing-shotgun-shell.png",
                    StackSize = 200,
                    Subgroup = "ammo",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "ammo",
                    Name = "cannon-shell",
                    Icon = "graphics/icons/cannon-shell.png",
                    StackSize = 200,
                    Subgroup = "ammo",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "ammo",
                    Name = "uranium-rounds-magazine",
                    Icon = "graphics/icons/uranium-rounds-magazine.png",
                    StackSize = 200,
                    Subgroup = "ammo",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "ammo",
                    Name = "flamethrower-ammo",
                    Icon = "graphics/icons/flamethrower-ammo.png",
                    StackSize = 100,
                    Subgroup = "ammo",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "armor",
                    Name = "heavy-armor",
                    Icon = "graphics/icons/heavy-armor.png",
                    StackSize = 1,
                    Subgroup = "armor",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "armor",
                    Name = "power-armor",
                    Icon = "graphics/icons/power-armor.png",
                    StackSize = 1,
                    Subgroup = "armor",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "armor",
                    Name = "modular-armor",
                    Icon = "graphics/icons/modular-armor.png",
                    StackSize = 1,
                    Subgroup = "armor",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "armor",
                    Name = "light-armor",
                    Icon = "graphics/icons/light-armor.png",
                    StackSize = 1,
                    Subgroup = "armor",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "armor",
                    Name = "power-armor-mk2",
                    Icon = "graphics/icons/power-armor-mk2.png",
                    StackSize = 1,
                    Subgroup = "armor",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "capsule",
                    Name = "grenade",
                    Icon = "graphics/icons/grenade.png",
                    StackSize = 100,
                    Subgroup = "capsule",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "capsule",
                    Name = "defender-capsule",
                    Icon = "graphics/icons/defender.png",
                    StackSize = 100,
                    Subgroup = "capsule",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "capsule",
                    Name = "slowdown-capsule",
                    Icon = "graphics/icons/slowdown-capsule.png",
                    StackSize = 100,
                    Subgroup = "capsule",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "capsule",
                    Name = "cliff-explosives",
                    Icon = "graphics/icons/cliff-explosives.png",
                    StackSize = 20,
                    Subgroup = "terrain",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "capsule",
                    Name = "poison-capsule",
                    Icon = "graphics/icons/poison-capsule.png",
                    StackSize = 100,
                    Subgroup = "capsule",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "capsule",
                    Name = "destroyer-capsule",
                    Icon = "graphics/icons/destroyer.png",
                    StackSize = 100,
                    Subgroup = "capsule",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "capsule",
                    Name = "artillery-targeting-remote",
                    Icon = "graphics/icons/artillery-targeting-remote.png",
                    StackSize = 1,
                    Subgroup = "capsule",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "capsule",
                    Name = "cluster-grenade",
                    Icon = "graphics/icons/cluster-grenade.png",
                    StackSize = 100,
                    Subgroup = "capsule",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "capsule",
                    Name = "discharge-defense-remote",
                    Icon = "graphics/equipment/discharge-defense-equipment-ability.png",
                    StackSize = 1,
                    Subgroup = "capsule",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "capsule",
                    Name = "distractor-capsule",
                    Icon = "graphics/icons/distractor.png",
                    StackSize = 100,
                    Subgroup = "capsule",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "capsule",
                    Name = "raw-fish",
                    Icon = "graphics/icons/fish.png",
                    StackSize = 100,
                    Subgroup = "raw-resource",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "fluid",
                    Name = "light-oil",
                    Icon = "graphics/icons/fluid/light-oil.png",
                    StackSize = 0,
                    Subgroup = "null",
                    Fluid = true,
                },
                new FactorioEntity {
                    Type = "fluid",
                    Name = "heavy-oil",
                    Icon = "graphics/icons/fluid/heavy-oil.png",
                    StackSize = 0,
                    Subgroup = "null",
                    Fluid = true,
                },
                new FactorioEntity {
                    Type = "fluid",
                    Name = "crude-oil",
                    Icon = "graphics/icons/fluid/crude-oil.png",
                    StackSize = 0,
                    Subgroup = "null",
                    Fluid = true,
                },
                new FactorioEntity {
                    Type = "fluid",
                    Name = "petroleum-gas",
                    Icon = "graphics/icons/fluid/petroleum-gas.png",
                    StackSize = 0,
                    Subgroup = "null",
                    Fluid = true,
                },
                new FactorioEntity {
                    Type = "fluid",
                    Name = "water",
                    Icon = "graphics/icons/fluid/water.png",
                    StackSize = 0,
                    Subgroup = "null",
                    Fluid = true,
                },
                new FactorioEntity {
                    Type = "fluid",
                    Name = "lubricant",
                    Icon = "graphics/icons/fluid/lubricant.png",
                    StackSize = 0,
                    Subgroup = "null",
                    Fluid = true,
                },
                new FactorioEntity {
                    Type = "fluid",
                    Name = "steam",
                    Icon = "graphics/icons/fluid/steam.png",
                    StackSize = 0,
                    Subgroup = "null",
                    Fluid = true,
                },
                new FactorioEntity {
                    Type = "fluid",
                    Name = "sulfuric-acid",
                    Icon = "graphics/icons/fluid/sulfuric-acid.png",
                    StackSize = 0,
                    Subgroup = "null",
                    Fluid = true,
                },
                new FactorioEntity {
                    Type = "gun",
                    Name = "tank-machine-gun",
                    Icon = "graphics/icons/submachine-gun.png",
                    StackSize = 1,
                    Subgroup = "gun",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "gun",
                    Name = "shotgun",
                    Icon = "graphics/icons/shotgun.png",
                    StackSize = 5,
                    Subgroup = "gun",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "gun",
                    Name = "vehicle-machine-gun",
                    Icon = "graphics/icons/submachine-gun.png",
                    StackSize = 1,
                    Subgroup = "gun",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "gun",
                    Name = "submachine-gun",
                    Icon = "graphics/icons/submachine-gun.png",
                    StackSize = 5,
                    Subgroup = "gun",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "gun",
                    Name = "railgun",
                    Icon = "graphics/icons/railgun.png",
                    StackSize = 5,
                    Subgroup = "gun",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "gun",
                    Name = "artillery-wagon-cannon",
                    Icon = "graphics/icons/tank-cannon.png",
                    StackSize = 1,
                    Subgroup = "gun",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "gun",
                    Name = "rocket-launcher",
                    Icon = "graphics/icons/rocket-launcher.png",
                    StackSize = 5,
                    Subgroup = "gun",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "gun",
                    Name = "tank-cannon",
                    Icon = "graphics/icons/tank-cannon.png",
                    StackSize = 5,
                    Subgroup = "gun",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "gun",
                    Name = "tank-flamethrower",
                    Icon = "graphics/icons/flamethrower.png",
                    StackSize = 1,
                    Subgroup = "gun",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "gun",
                    Name = "flamethrower",
                    Icon = "graphics/icons/flamethrower.png",
                    StackSize = 5,
                    Subgroup = "gun",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "gun",
                    Name = "combat-shotgun",
                    Icon = "graphics/icons/combat-shotgun.png",
                    StackSize = 5,
                    Subgroup = "gun",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "gun",
                    Name = "pistol",
                    Icon = "graphics/icons/pistol.png",
                    StackSize = 5,
                    Subgroup = "gun",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "simple-entity-with-force",
                    Icon = "graphics/icons/steel-chest.png",
                    StackSize = 50,
                    Subgroup = "other",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "rocket-silo",
                    Icon = "graphics/icons/rocket-silo.png",
                    StackSize = 1,
                    Subgroup = "defensive-structure",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "small-electric-pole",
                    Icon = "graphics/icons/small-electric-pole.png",
                    StackSize = 50,
                    Subgroup = "energy-pipe-distribution",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "crash-site-lab-repaired",
                    Icon = "graphics/icons/crash-site-lab-repaired.png",
                    StackSize = 1,
                    Subgroup = "crash-site",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "copper-ore",
                    Icon = "graphics/icons/copper-ore.png",
                    StackSize = 50,
                    Subgroup = "raw-resource",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "chemical-plant",
                    Icon = "graphics/icons/chemical-plant.png",
                    StackSize = 10,
                    Subgroup = "production-machine",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "burner-generator",
                    Icon = "graphics/icons/steam-engine.png",
                    StackSize = 10,
                    Subgroup = "other",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "underground-belt",
                    Icon = "graphics/icons/underground-belt.png",
                    StackSize = 50,
                    Subgroup = "belt",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "crash-site-assembling-machine-1-repaired",
                    Icon = "graphics/icons/crash-site-assembling-machine-1-repaired.png",
                    StackSize = 1,
                    Subgroup = "crash-site",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "logistic-chest-active-provider",
                    Icon = "graphics/icons/logistic-chest-active-provider.png",
                    StackSize = 50,
                    Subgroup = "logistic-network",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "big-electric-pole",
                    Icon = "graphics/icons/big-electric-pole.png",
                    StackSize = 50,
                    Subgroup = "energy-pipe-distribution",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "uranium-238",
                    Icon = "graphics/icons/uranium-238.png",
                    StackSize = 100,
                    Subgroup = "intermediate-product",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "constant-combinator",
                    Icon = "graphics/icons/constant-combinator.png",
                    StackSize = 50,
                    Subgroup = "circuit-network",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "iron-stick",
                    Icon = "graphics/icons/iron-stick.png",
                    StackSize = 100,
                    Subgroup = "intermediate-product",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "decider-combinator",
                    Icon = "graphics/icons/decider-combinator.png",
                    StackSize = 50,
                    Subgroup = "circuit-network",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "fast-loader",
                    Icon = "graphics/icons/fast-loader.png",
                    StackSize = 50,
                    Subgroup = "belt",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "express-transport-belt",
                    Icon = "graphics/icons/express-transport-belt.png",
                    StackSize = 100,
                    Subgroup = "belt",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "uranium-235",
                    Icon = "graphics/icons/uranium-235.png",
                    StackSize = 100,
                    Subgroup = "intermediate-product",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "infinity-chest",
                    Icon = "graphics/icons/infinity-chest.png",
                    StackSize = 10,
                    Subgroup = "other",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "copper-cable",
                    Icon = "graphics/icons/copper-cable.png",
                    StackSize = 200,
                    Subgroup = "intermediate-product",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "engine-unit",
                    Icon = "graphics/icons/engine-unit.png",
                    StackSize = 50,
                    Subgroup = "intermediate-product",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "crash-site-assembling-machine-1-broken",
                    Icon = "graphics/icons/crash-site-assembling-machine-1-broken.png",
                    StackSize = 1,
                    Subgroup = "crash-site",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "logistic-chest-passive-provider",
                    Icon = "graphics/icons/logistic-chest-passive-provider.png",
                    StackSize = 50,
                    Subgroup = "logistic-network",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "burner-inserter",
                    Icon = "graphics/icons/burner-inserter.png",
                    StackSize = 50,
                    Subgroup = "inserter",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "steel-chest",
                    Icon = "graphics/icons/steel-chest.png",
                    StackSize = 50,
                    Subgroup = "storage",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "crash-site-assembling-machine-2-broken",
                    Icon = "graphics/icons/crash-site-assembling-machine-2-broken.png",
                    StackSize = 1,
                    Subgroup = "crash-site",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "crude-oil-barrel",
                    Icon = "",
                    StackSize = 10,
                    Subgroup = "fill-barrel",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "land-mine",
                    Icon = "graphics/icons/land-mine.png",
                    StackSize = 100,
                    Subgroup = "gun",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "small-lamp",
                    Icon = "graphics/icons/small-lamp.png",
                    StackSize = 50,
                    Subgroup = "circuit-network",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "nuclear-fuel",
                    Icon = "graphics/icons/nuclear-fuel.png",
                    StackSize = 1,
                    Subgroup = "intermediate-product",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "electric-furnace",
                    Icon = "graphics/icons/electric-furnace.png",
                    StackSize = 50,
                    Subgroup = "smelting-machine",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "splitter",
                    Icon = "graphics/icons/splitter.png",
                    StackSize = 50,
                    Subgroup = "belt",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "arithmetic-combinator",
                    Icon = "graphics/icons/arithmetic-combinator.png",
                    StackSize = 50,
                    Subgroup = "circuit-network",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "loader",
                    Icon = "graphics/icons/loader.png",
                    StackSize = 50,
                    Subgroup = "belt",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "steam-engine",
                    Icon = "graphics/icons/steam-engine.png",
                    StackSize = 10,
                    Subgroup = "energy",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "personal-laser-defense-equipment",
                    Icon = "graphics/icons/personal-laser-defense-equipment.png",
                    StackSize = 20,
                    Subgroup = "equipment",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "flamethrower-turret",
                    Icon = "graphics/icons/flamethrower-turret.png",
                    StackSize = 50,
                    Subgroup = "defensive-structure",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "petroleum-gas-barrel",
                    Icon = "",
                    StackSize = 10,
                    Subgroup = "fill-barrel",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "gate",
                    Icon = "graphics/icons/gate.png",
                    StackSize = 50,
                    Subgroup = "defensive-structure",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "iron-ore",
                    Icon = "graphics/icons/iron-ore.png",
                    StackSize = 50,
                    Subgroup = "raw-resource",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "energy-shield-equipment",
                    Icon = "graphics/icons/energy-shield-equipment.png",
                    StackSize = 20,
                    Subgroup = "equipment",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "heat-exchanger",
                    Icon = "graphics/icons/heat-boiler.png",
                    StackSize = 50,
                    Subgroup = "energy",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "storage-tank",
                    Icon = "graphics/icons/storage-tank.png",
                    StackSize = 50,
                    Subgroup = "storage",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "inserter",
                    Icon = "graphics/icons/inserter.png",
                    StackSize = 50,
                    Subgroup = "inserter",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "personal-roboport-equipment",
                    Icon = "graphics/icons/personal-roboport-equipment.png",
                    StackSize = 20,
                    Subgroup = "equipment",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "stone-furnace",
                    Icon = "graphics/icons/stone-furnace.png",
                    StackSize = 50,
                    Subgroup = "smelting-machine",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "compilatron-chest",
                    Icon = "graphics/icons/compilatron-chest.png",
                    StackSize = 50,
                    Subgroup = "storage",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "fast-underground-belt",
                    Icon = "graphics/icons/fast-underground-belt.png",
                    StackSize = 50,
                    Subgroup = "belt",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "refined-hazard-concrete",
                    Icon = "graphics/icons/refined-hazard-concrete.png",
                    StackSize = 100,
                    Subgroup = "terrain",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "crash-site-chest-1",
                    Icon = "graphics/icons/crash-site-chest.png",
                    StackSize = 1,
                    Subgroup = "crash-site",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "fusion-reactor-equipment",
                    Icon = "graphics/icons/fusion-reactor-equipment.png",
                    StackSize = 20,
                    Subgroup = "equipment",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "small-plane",
                    Icon = "graphics/icons/small-plane.png",
                    StackSize = 1,
                    Subgroup = "transport",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "processing-unit",
                    Icon = "graphics/icons/processing-unit.png",
                    StackSize = 100,
                    Subgroup = "intermediate-product",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "fast-transport-belt",
                    Icon = "graphics/icons/fast-transport-belt.png",
                    StackSize = 100,
                    Subgroup = "belt",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "hazard-concrete",
                    Icon = "graphics/icons/hazard-concrete.png",
                    StackSize = 100,
                    Subgroup = "terrain",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "heat-interface",
                    Icon = "graphics/icons/heat-interface.png",
                    StackSize = 20,
                    Subgroup = "other",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "iron-chest",
                    Icon = "graphics/icons/iron-chest.png",
                    StackSize = 50,
                    Subgroup = "storage",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "electric-energy-interface",
                    Icon = "",
                    StackSize = 50,
                    Subgroup = "other",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "burner-mining-drill",
                    Icon = "graphics/icons/burner-mining-drill.png",
                    StackSize = 50,
                    Subgroup = "extraction-machine",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "sulfur",
                    Icon = "graphics/icons/sulfur.png",
                    StackSize = 50,
                    Subgroup = "raw-material",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "crash-site-generator",
                    Icon = "graphics/icons/crash-site-generator.png",
                    StackSize = 1,
                    Subgroup = "crash-site",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "accumulator",
                    Icon = "graphics/icons/accumulator.png",
                    StackSize = 50,
                    Subgroup = "energy",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "energy-shield-mk2-equipment",
                    Icon = "graphics/icons/energy-shield-mk2-equipment.png",
                    StackSize = 20,
                    Subgroup = "equipment",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "simple-entity-with-owner",
                    Icon = "graphics/icons/wooden-chest.png",
                    StackSize = 50,
                    Subgroup = "other",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "solid-fuel",
                    Icon = "graphics/icons/solid-fuel.png",
                    StackSize = 50,
                    Subgroup = "raw-material",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "coin",
                    Icon = "graphics/icons/coin.png",
                    StackSize = 100000,
                    Subgroup = "science-pack",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "empty-barrel",
                    Icon = "graphics/icons/fluid/barreling/empty-barrel.png",
                    StackSize = 10,
                    Subgroup = "intermediate-product",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "construction-robot",
                    Icon = "graphics/icons/construction-robot.png",
                    StackSize = 50,
                    Subgroup = "logistic-network",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "heat-pipe",
                    Icon = "graphics/icons/heat-pipe.png",
                    StackSize = 50,
                    Subgroup = "energy",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "oil-refinery",
                    Icon = "graphics/icons/oil-refinery.png",
                    StackSize = 10,
                    Subgroup = "production-machine",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "roboport",
                    Icon = "graphics/icons/roboport.png",
                    StackSize = 10,
                    Subgroup = "logistic-network",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "battery-mk2-equipment",
                    Icon = "graphics/icons/battery-mk2-equipment.png",
                    StackSize = 20,
                    Subgroup = "equipment",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "plastic-bar",
                    Icon = "graphics/icons/plastic-bar.png",
                    StackSize = 100,
                    Subgroup = "raw-material",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "lab",
                    Icon = "graphics/icons/lab.png",
                    StackSize = 10,
                    Subgroup = "production-machine",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "beacon",
                    Icon = "graphics/icons/beacon.png",
                    StackSize = 10,
                    Subgroup = "module",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "artillery-turret",
                    Icon = "graphics/icons/artillery-turret.png",
                    StackSize = 10,
                    Subgroup = "defensive-structure",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "express-splitter",
                    Icon = "graphics/icons/express-splitter.png",
                    StackSize = 50,
                    Subgroup = "belt",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "infinity-pipe",
                    Icon = "",
                    StackSize = 10,
                    Subgroup = "other",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "crash-site-assembling-machine-2-repaired",
                    Icon = "graphics/icons/crash-site-assembling-machine-2-repaired.png",
                    StackSize = 1,
                    Subgroup = "crash-site",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "crash-site-chest-2",
                    Icon = "graphics/icons/crash-site-chest.png",
                    StackSize = 1,
                    Subgroup = "crash-site",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "power-switch",
                    Icon = "graphics/icons/power-switch.png",
                    StackSize = 50,
                    Subgroup = "circuit-network",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "stone",
                    Icon = "graphics/icons/stone.png",
                    StackSize = 50,
                    Subgroup = "raw-resource",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "explosives",
                    Icon = "graphics/icons/explosives.png",
                    StackSize = 50,
                    Subgroup = "raw-material",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "sulfuric-acid-barrel",
                    Icon = "",
                    StackSize = 10,
                    Subgroup = "fill-barrel",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "centrifuge",
                    Icon = "graphics/icons/centrifuge.png",
                    StackSize = 50,
                    Subgroup = "production-machine",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "assembling-machine-2",
                    Icon = "graphics/icons/assembling-machine-2.png",
                    StackSize = 50,
                    Subgroup = "production-machine",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "flying-robot-frame",
                    Icon = "graphics/icons/flying-robot-frame.png",
                    StackSize = 50,
                    Subgroup = "intermediate-product",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "uranium-ore",
                    Icon = "graphics/icons/uranium-ore.png",
                    StackSize = 50,
                    Subgroup = "raw-resource",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "satellite",
                    Icon = "graphics/icons/satellite.png",
                    StackSize = 1,
                    Subgroup = "intermediate-product",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "fast-inserter",
                    Icon = "graphics/icons/fast-inserter.png",
                    StackSize = 50,
                    Subgroup = "inserter",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "solar-panel-equipment",
                    Icon = "graphics/icons/solar-panel-equipment.png",
                    StackSize = 20,
                    Subgroup = "equipment",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "logistic-chest-requester",
                    Icon = "graphics/icons/logistic-chest-requester.png",
                    StackSize = 50,
                    Subgroup = "logistic-network",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "water-barrel",
                    Icon = "",
                    StackSize = 10,
                    Subgroup = "fill-barrel",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "assembling-machine-1",
                    Icon = "graphics/icons/assembling-machine-1.png",
                    StackSize = 50,
                    Subgroup = "production-machine",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "logistic-chest-buffer",
                    Icon = "graphics/icons/logistic-chest-buffer.png",
                    StackSize = 50,
                    Subgroup = "logistic-network",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "battery-equipment",
                    Icon = "graphics/icons/battery-equipment.png",
                    StackSize = 20,
                    Subgroup = "equipment",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "personal-roboport-mk2-equipment",
                    Icon = "graphics/icons/personal-roboport-mk2-equipment.png",
                    StackSize = 20,
                    Subgroup = "equipment",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "light-oil-barrel",
                    Icon = "",
                    StackSize = 10,
                    Subgroup = "fill-barrel",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "rocket-part",
                    Icon = "graphics/icons/rocket-part.png",
                    StackSize = 5,
                    Subgroup = "intermediate-product",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "stack-inserter",
                    Icon = "graphics/icons/stack-inserter.png",
                    StackSize = 50,
                    Subgroup = "inserter",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "low-density-structure",
                    Icon = "graphics/icons/low-density-structure.png",
                    StackSize = 10,
                    Subgroup = "intermediate-product",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "battery",
                    Icon = "graphics/icons/battery.png",
                    StackSize = 200,
                    Subgroup = "raw-material",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "used-up-uranium-fuel-cell",
                    Icon = "graphics/icons/used-up-uranium-fuel-cell.png",
                    StackSize = 50,
                    Subgroup = "intermediate-product",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "gun-turret",
                    Icon = "graphics/icons/gun-turret.png",
                    StackSize = 50,
                    Subgroup = "defensive-structure",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "filter-inserter",
                    Icon = "graphics/icons/filter-inserter.png",
                    StackSize = 50,
                    Subgroup = "inserter",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "wooden-chest",
                    Icon = "graphics/icons/wooden-chest.png",
                    StackSize = 50,
                    Subgroup = "storage",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "stone-wall",
                    Icon = "graphics/icons/wall.png",
                    StackSize = 100,
                    Subgroup = "defensive-structure",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "wood",
                    Icon = "graphics/icons/wood.png",
                    StackSize = 100,
                    Subgroup = "raw-resource",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "uranium-fuel-cell",
                    Icon = "graphics/icons/uranium-fuel-cell.png",
                    StackSize = 50,
                    Subgroup = "intermediate-product",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "belt-immunity-equipment",
                    Icon = "graphics/icons/belt-immunity-equipment.png",
                    StackSize = 20,
                    Subgroup = "equipment",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "transport-belt",
                    Icon = "graphics/icons/transport-belt.png",
                    StackSize = 100,
                    Subgroup = "belt",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "copper-plate",
                    Icon = "graphics/icons/copper-plate.png",
                    StackSize = 100,
                    Subgroup = "raw-material",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "rail-signal",
                    Icon = "graphics/icons/rail-signal.png",
                    StackSize = 50,
                    Subgroup = "transport",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "advanced-circuit",
                    Icon = "graphics/icons/advanced-circuit.png",
                    StackSize = 200,
                    Subgroup = "intermediate-product",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "train-stop",
                    Icon = "graphics/icons/train-stop.png",
                    StackSize = 10,
                    Subgroup = "transport",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "medium-electric-pole",
                    Icon = "graphics/icons/medium-electric-pole.png",
                    StackSize = 50,
                    Subgroup = "energy-pipe-distribution",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "substation",
                    Icon = "graphics/icons/substation.png",
                    StackSize = 50,
                    Subgroup = "energy-pipe-distribution",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "crash-site-electric-pole",
                    Icon = "graphics/icons/crash-site-electric-pole.png",
                    StackSize = 1,
                    Subgroup = "crash-site",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "stone-brick",
                    Icon = "graphics/icons/stone-brick.png",
                    StackSize = 100,
                    Subgroup = "terrain",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "steel-plate",
                    Icon = "graphics/icons/steel-plate.png",
                    StackSize = 100,
                    Subgroup = "raw-material",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "pipe-to-ground",
                    Icon = "graphics/icons/pipe-to-ground.png",
                    StackSize = 50,
                    Subgroup = "energy-pipe-distribution",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "solar-panel",
                    Icon = "graphics/icons/solar-panel.png",
                    StackSize = 50,
                    Subgroup = "energy",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "stack-filter-inserter",
                    Icon = "graphics/icons/stack-filter-inserter.png",
                    StackSize = 50,
                    Subgroup = "inserter",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "steam-turbine",
                    Icon = "graphics/icons/steam-turbine.png",
                    StackSize = 10,
                    Subgroup = "energy",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "concrete",
                    Icon = "graphics/icons/concrete.png",
                    StackSize = 100,
                    Subgroup = "terrain",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "rocket-control-unit",
                    Icon = "graphics/icons/rocket-control-unit.png",
                    StackSize = 10,
                    Subgroup = "intermediate-product",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "refined-concrete",
                    Icon = "graphics/icons/refined-concrete.png",
                    StackSize = 100,
                    Subgroup = "terrain",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "night-vision-equipment",
                    Icon = "graphics/icons/night-vision-equipment.png",
                    StackSize = 20,
                    Subgroup = "equipment",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "electric-mining-drill",
                    Icon = "graphics/icons/electric-mining-drill.png",
                    StackSize = 50,
                    Subgroup = "extraction-machine",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "crash-site-lab-broken",
                    Icon = "graphics/icons/crash-site-lab-broken.png",
                    StackSize = 1,
                    Subgroup = "crash-site",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "radar",
                    Icon = "graphics/icons/radar.png",
                    StackSize = 50,
                    Subgroup = "defensive-structure",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "boiler",
                    Icon = "graphics/icons/boiler.png",
                    StackSize = 50,
                    Subgroup = "energy",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "landfill",
                    Icon = "graphics/icons/landfill.png",
                    StackSize = 100,
                    Subgroup = "terrain",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "pumpjack",
                    Icon = "graphics/icons/pumpjack.png",
                    StackSize = 20,
                    Subgroup = "extraction-machine",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "coal",
                    Icon = "graphics/icons/coal.png",
                    StackSize = 50,
                    Subgroup = "raw-resource",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "pump",
                    Icon = "graphics/icons/pump.png",
                    StackSize = 50,
                    Subgroup = "energy-pipe-distribution",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "iron-gear-wheel",
                    Icon = "graphics/icons/iron-gear-wheel.png",
                    StackSize = 100,
                    Subgroup = "intermediate-product",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "programmable-speaker",
                    Icon = "graphics/icons/programmable-speaker.png",
                    StackSize = 50,
                    Subgroup = "circuit-network",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "player-port",
                    Icon = "graphics/icons/player-port.png",
                    StackSize = 50,
                    Subgroup = "defensive-structure",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "steel-furnace",
                    Icon = "graphics/icons/steel-furnace.png",
                    StackSize = 50,
                    Subgroup = "smelting-machine",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "nuclear-reactor",
                    Icon = "graphics/icons/nuclear-reactor.png",
                    StackSize = 10,
                    Subgroup = "energy",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "pipe",
                    Icon = "graphics/icons/pipe.png",
                    StackSize = 100,
                    Subgroup = "energy-pipe-distribution",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "offshore-pump",
                    Icon = "graphics/icons/offshore-pump.png",
                    StackSize = 20,
                    Subgroup = "extraction-machine",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "red-wire",
                    Icon = "graphics/icons/red-wire.png",
                    StackSize = 200,
                    Subgroup = "circuit-network",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "logistic-chest-storage",
                    Icon = "graphics/icons/logistic-chest-storage.png",
                    StackSize = 50,
                    Subgroup = "logistic-network",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "lubricant-barrel",
                    Icon = "",
                    StackSize = 10,
                    Subgroup = "fill-barrel",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "long-handed-inserter",
                    Icon = "graphics/icons/long-handed-inserter.png",
                    StackSize = 50,
                    Subgroup = "inserter",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "logistic-robot",
                    Icon = "graphics/icons/logistic-robot.png",
                    StackSize = 50,
                    Subgroup = "logistic-network",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "electronic-circuit",
                    Icon = "graphics/icons/electronic-circuit.png",
                    StackSize = 200,
                    Subgroup = "intermediate-product",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "iron-plate",
                    Icon = "graphics/icons/iron-plate.png",
                    StackSize = 100,
                    Subgroup = "raw-material",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "assembling-machine-3",
                    Icon = "graphics/icons/assembling-machine-3.png",
                    StackSize = 50,
                    Subgroup = "production-machine",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "heavy-oil-barrel",
                    Icon = "",
                    StackSize = 10,
                    Subgroup = "fill-barrel",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "green-wire",
                    Icon = "graphics/icons/green-wire.png",
                    StackSize = 200,
                    Subgroup = "circuit-network",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "fast-splitter",
                    Icon = "graphics/icons/fast-splitter.png",
                    StackSize = 50,
                    Subgroup = "belt",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "laser-turret",
                    Icon = "graphics/icons/laser-turret.png",
                    StackSize = 50,
                    Subgroup = "defensive-structure",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "express-loader",
                    Icon = "graphics/icons/express-loader.png",
                    StackSize = 50,
                    Subgroup = "belt",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "exoskeleton-equipment",
                    Icon = "graphics/icons/exoskeleton-equipment.png",
                    StackSize = 20,
                    Subgroup = "equipment",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "express-underground-belt",
                    Icon = "graphics/icons/express-underground-belt.png",
                    StackSize = 50,
                    Subgroup = "belt",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "electric-engine-unit",
                    Icon = "graphics/icons/electric-engine-unit.png",
                    StackSize = 50,
                    Subgroup = "intermediate-product",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "computer",
                    Icon = "graphics/icons/computer.png",
                    StackSize = 1,
                    Subgroup = "defensive-structure",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "rail-chain-signal",
                    Icon = "graphics/icons/rail-chain-signal.png",
                    StackSize = 50,
                    Subgroup = "transport",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "discharge-defense-equipment",
                    Icon = "graphics/icons/discharge-defense-equipment.png",
                    StackSize = 20,
                    Subgroup = "equipment",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "item",
                    Name = "rocket-fuel",
                    Icon = "graphics/icons/rocket-fuel.png",
                    StackSize = 10,
                    Subgroup = "intermediate-product",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "module",
                    Name = "effectivity-module-2",
                    Icon = "graphics/icons/effectivity-module-2.png",
                    StackSize = 50,
                    Subgroup = "module",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "module",
                    Name = "effectivity-module-3",
                    Icon = "graphics/icons/effectivity-module-3.png",
                    StackSize = 50,
                    Subgroup = "module",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "module",
                    Name = "effectivity-module",
                    Icon = "graphics/icons/effectivity-module.png",
                    StackSize = 50,
                    Subgroup = "module",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "module",
                    Name = "speed-module-2",
                    Icon = "graphics/icons/speed-module-2.png",
                    StackSize = 50,
                    Subgroup = "module",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "module",
                    Name = "productivity-module-2",
                    Icon = "graphics/icons/productivity-module-2.png",
                    StackSize = 50,
                    Subgroup = "module",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "module",
                    Name = "productivity-module-3",
                    Icon = "graphics/icons/productivity-module-3.png",
                    StackSize = 50,
                    Subgroup = "module",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "module",
                    Name = "speed-module-3",
                    Icon = "graphics/icons/speed-module-3.png",
                    StackSize = 50,
                    Subgroup = "module",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "module",
                    Name = "speed-module",
                    Icon = "graphics/icons/speed-module.png",
                    StackSize = 50,
                    Subgroup = "module",
                    Fluid = false,
                },
                new FactorioEntity {
                    Type = "module",
                    Name = "productivity-module",
                    Icon = "graphics/icons/productivity-module.png",
                    StackSize = 50,
                    Subgroup = "module",
                    Fluid = false,
                },
            };
        }
    }
}
