// <auto-generated />
using System;
using FNO.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace FNO.Domain.Migrations
{
    [DbContext(typeof(ReadModelDbContext))]
    [Migration("20180627122154_Seed")]
    partial class Seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("FNO.Domain.Models.Corporation", b =>
                {
                    b.Property<Guid>("CorporationId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Credits");

                    b.HasKey("CorporationId");

                    b.ToTable("Corporations");
                });

            modelBuilder.Entity("FNO.Domain.Models.FactorioEntity", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Fluid");

                    b.Property<string>("Icon");

                    b.Property<int>("StackSize");

                    b.Property<string>("Subgroup");

                    b.Property<string>("Type");

                    b.HasKey("Name");

                    b.ToTable("EntityLibrary");

                    b.HasData(
                        new { Name = "crude-oil", Fluid = true, Icon = "graphics/icons/fluid/crude-oil.png", StackSize = 0, Type = "fluid" },
                        new { Name = "heavy-oil", Fluid = true, Icon = "graphics/icons/fluid/heavy-oil.png", StackSize = 0, Type = "fluid" },
                        new { Name = "light-oil", Fluid = true, Icon = "graphics/icons/fluid/light-oil.png", StackSize = 0, Type = "fluid" },
                        new { Name = "petroleum-gas", Fluid = true, Icon = "graphics/icons/fluid/petroleum-gas.png", StackSize = 0, Type = "fluid" },
                        new { Name = "lubricant", Fluid = true, Icon = "graphics/icons/fluid/lubricant.png", StackSize = 0, Type = "fluid" },
                        new { Name = "sulfuric-acid", Fluid = true, Icon = "graphics/icons/fluid/sulfuric-acid.png", StackSize = 0, Type = "fluid" },
                        new { Name = "water", Fluid = true, Icon = "graphics/icons/fluid/water.png", StackSize = 0, Type = "fluid" },
                        new { Name = "steam", Fluid = true, Icon = "graphics/icons/fluid/steam.png", StackSize = 0, Type = "fluid" },
                        new { Name = "solar-panel-equipment", Fluid = false, Icon = "graphics/icons/solar-panel-equipment.png", StackSize = 20, Subgroup = "equipment", Type = "item" },
                        new { Name = "fusion-reactor-equipment", Fluid = false, Icon = "graphics/icons/fusion-reactor-equipment.png", StackSize = 20, Subgroup = "equipment", Type = "item" },
                        new { Name = "energy-shield-equipment", Fluid = false, Icon = "graphics/icons/energy-shield-equipment.png", StackSize = 50, Subgroup = "equipment", Type = "item" },
                        new { Name = "energy-shield-mk2-equipment", Fluid = false, Icon = "graphics/icons/energy-shield-mk2-equipment.png", StackSize = 50, Subgroup = "equipment", Type = "item" },
                        new { Name = "battery-equipment", Fluid = false, Icon = "graphics/icons/battery-equipment.png", StackSize = 50, Subgroup = "equipment", Type = "item" },
                        new { Name = "battery-mk2-equipment", Fluid = false, Icon = "graphics/icons/battery-mk2-equipment.png", StackSize = 50, Subgroup = "equipment", Type = "item" },
                        new { Name = "personal-laser-defense-equipment", Fluid = false, Icon = "graphics/icons/personal-laser-defense-equipment.png", StackSize = 20, Subgroup = "equipment", Type = "item" },
                        new { Name = "discharge-defense-equipment", Fluid = false, Icon = "graphics/icons/discharge-defense-equipment.png", StackSize = 20, Subgroup = "equipment", Type = "item" },
                        new { Name = "exoskeleton-equipment", Fluid = false, Icon = "graphics/icons/exoskeleton-equipment.png", StackSize = 10, Subgroup = "equipment", Type = "item" },
                        new { Name = "personal-roboport-equipment", Fluid = false, Icon = "graphics/icons/personal-roboport-equipment.png", StackSize = 5, Subgroup = "equipment", Type = "item" },
                        new { Name = "personal-roboport-mk2-equipment", Fluid = false, Icon = "graphics/icons/personal-roboport-mk2-equipment.png", StackSize = 5, Subgroup = "equipment", Type = "item" },
                        new { Name = "night-vision-equipment", Fluid = false, Icon = "graphics/icons/night-vision-equipment.png", StackSize = 20, Subgroup = "equipment", Type = "item" },
                        new { Name = "belt-immunity-equipment", Fluid = false, Icon = "graphics/icons/belt-immunity-equipment.png", StackSize = 1, Subgroup = "equipment", Type = "item" },
                        new { Name = "iron-axe", Fluid = false, Icon = "graphics/icons/iron-axe.png", StackSize = 20, Subgroup = "tool", Type = "mining-tool" },
                        new { Name = "steel-axe", Fluid = false, Icon = "graphics/icons/steel-axe.png", StackSize = 20, Subgroup = "tool", Type = "mining-tool" },
                        new { Name = "stone-brick", Fluid = false, Icon = "graphics/icons/stone-brick.png", StackSize = 100, Subgroup = "terrain", Type = "item" },
                        new { Name = "raw-wood", Fluid = false, Icon = "graphics/icons/raw-wood.png", StackSize = 100, Subgroup = "raw-resource", Type = "item" },
                        new { Name = "coal", Fluid = false, Icon = "graphics/icons/coal.png", StackSize = 50, Subgroup = "raw-resource", Type = "item" },
                        new { Name = "stone", Fluid = false, Icon = "graphics/icons/stone.png", StackSize = 50, Subgroup = "raw-resource", Type = "item" },
                        new { Name = "iron-ore", Fluid = false, Icon = "graphics/icons/iron-ore.png", StackSize = 50, Subgroup = "raw-resource", Type = "item" },
                        new { Name = "copper-ore", Fluid = false, Icon = "graphics/icons/copper-ore.png", StackSize = 50, Subgroup = "raw-resource", Type = "item" },
                        new { Name = "wood", Fluid = false, Icon = "graphics/icons/wood.png", StackSize = 50, Subgroup = "raw-material", Type = "item" },
                        new { Name = "iron-plate", Fluid = false, Icon = "graphics/icons/iron-plate.png", StackSize = 100, Subgroup = "raw-material", Type = "item" },
                        new { Name = "copper-plate", Fluid = false, Icon = "graphics/icons/copper-plate.png", StackSize = 100, Subgroup = "raw-material", Type = "item" },
                        new { Name = "copper-cable", Fluid = false, Icon = "graphics/icons/copper-cable.png", StackSize = 200, Subgroup = "intermediate-product", Type = "item" },
                        new { Name = "iron-stick", Fluid = false, Icon = "graphics/icons/iron-stick.png", StackSize = 100, Subgroup = "intermediate-product", Type = "item" },
                        new { Name = "iron-gear-wheel", Fluid = false, Icon = "graphics/icons/iron-gear-wheel.png", StackSize = 100, Subgroup = "intermediate-product", Type = "item" },
                        new { Name = "electronic-circuit", Fluid = false, Icon = "graphics/icons/electronic-circuit.png", StackSize = 200, Subgroup = "intermediate-product", Type = "item" },
                        new { Name = "wooden-chest", Fluid = false, Icon = "graphics/icons/wooden-chest.png", StackSize = 50, Subgroup = "storage", Type = "item" },
                        new { Name = "stone-furnace", Fluid = false, Icon = "graphics/icons/stone-furnace.png", StackSize = 50, Subgroup = "smelting-machine", Type = "item" },
                        new { Name = "burner-mining-drill", Fluid = false, Icon = "graphics/icons/burner-mining-drill.png", StackSize = 50, Subgroup = "extraction-machine", Type = "item" },
                        new { Name = "electric-mining-drill", Fluid = false, Icon = "graphics/icons/electric-mining-drill.png", StackSize = 50, Subgroup = "extraction-machine", Type = "item" },
                        new { Name = "transport-belt", Fluid = false, Icon = "graphics/icons/transport-belt.png", StackSize = 100, Subgroup = "belt", Type = "item" },
                        new { Name = "burner-inserter", Fluid = false, Icon = "graphics/icons/burner-inserter.png", StackSize = 50, Subgroup = "inserter", Type = "item" },
                        new { Name = "inserter", Fluid = false, Icon = "graphics/icons/inserter.png", StackSize = 50, Subgroup = "inserter", Type = "item" },
                        new { Name = "offshore-pump", Fluid = false, Icon = "graphics/icons/offshore-pump.png", StackSize = 20, Subgroup = "extraction-machine", Type = "item" },
                        new { Name = "pipe", Fluid = false, Icon = "graphics/icons/pipe.png", StackSize = 100, Subgroup = "energy-pipe-distribution", Type = "item" },
                        new { Name = "boiler", Fluid = false, Icon = "graphics/icons/boiler.png", StackSize = 50, Subgroup = "energy", Type = "item" },
                        new { Name = "steam-engine", Fluid = false, Icon = "graphics/icons/steam-engine.png", StackSize = 10, Subgroup = "energy", Type = "item" },
                        new { Name = "small-electric-pole", Fluid = false, Icon = "graphics/icons/small-electric-pole.png", StackSize = 50, Subgroup = "energy-pipe-distribution", Type = "item" },
                        new { Name = "radar", Fluid = false, Icon = "graphics/icons/radar.png", StackSize = 50, Subgroup = "defensive-structure", Type = "item" },
                        new { Name = "computer", Fluid = false, Icon = "graphics/icons/computer.png", StackSize = 1, Subgroup = "defensive-structure", Type = "item" },
                        new { Name = "small-plane", Fluid = false, Icon = "graphics/icons/small-plane.png", StackSize = 1, Subgroup = "transport", Type = "item" },
                        new { Name = "small-lamp", Fluid = false, Icon = "graphics/icons/small-lamp.png", StackSize = 50, Subgroup = "circuit-network", Type = "item" },
                        new { Name = "pipe-to-ground", Fluid = false, Icon = "graphics/icons/pipe-to-ground.png", StackSize = 50, Subgroup = "energy-pipe-distribution", Type = "item" },
                        new { Name = "assembling-machine-1", Fluid = false, Icon = "graphics/icons/assembling-machine-1.png", StackSize = 50, Subgroup = "production-machine", Type = "item" },
                        new { Name = "red-wire", Fluid = false, Icon = "graphics/icons/red-wire.png", StackSize = 200, Subgroup = "circuit-network", Type = "item" },
                        new { Name = "green-wire", Fluid = false, Icon = "graphics/icons/green-wire.png", StackSize = 200, Subgroup = "circuit-network", Type = "item" },
                        new { Name = "raw-fish", Fluid = false, Icon = "graphics/icons/fish.png", StackSize = 100, Subgroup = "raw-resource", Type = "capsule" },
                        new { Name = "repair-pack", Fluid = false, Icon = "graphics/icons/repair-pack.png", StackSize = 100, Subgroup = "tool", Type = "repair-tool" },
                        new { Name = "stone-wall", Fluid = false, Icon = "graphics/icons/stone-wall.png", StackSize = 100, Subgroup = "defensive-structure", Type = "item" },
                        new { Name = "iron-chest", Fluid = false, Icon = "graphics/icons/iron-chest.png", StackSize = 50, Subgroup = "storage", Type = "item" },
                        new { Name = "steel-chest", Fluid = false, Icon = "graphics/icons/steel-chest.png", StackSize = 50, Subgroup = "storage", Type = "item" },
                        new { Name = "fast-transport-belt", Fluid = false, Icon = "graphics/icons/fast-transport-belt.png", StackSize = 100, Subgroup = "belt", Type = "item" },
                        new { Name = "express-transport-belt", Fluid = false, Icon = "graphics/icons/express-transport-belt.png", StackSize = 100, Subgroup = "belt", Type = "item" },
                        new { Name = "long-handed-inserter", Fluid = false, Icon = "graphics/icons/long-handed-inserter.png", StackSize = 50, Subgroup = "inserter", Type = "item" },
                        new { Name = "fast-inserter", Fluid = false, Icon = "graphics/icons/fast-inserter.png", StackSize = 50, Subgroup = "inserter", Type = "item" },
                        new { Name = "filter-inserter", Fluid = false, Icon = "graphics/icons/filter-inserter.png", StackSize = 50, Subgroup = "inserter", Type = "item" },
                        new { Name = "stack-inserter", Fluid = false, Icon = "graphics/icons/stack-inserter.png", StackSize = 50, Subgroup = "inserter", Type = "item" },
                        new { Name = "stack-filter-inserter", Fluid = false, Icon = "graphics/icons/stack-filter-inserter.png", StackSize = 50, Subgroup = "inserter", Type = "item" },
                        new { Name = "assembling-machine-2", Fluid = false, Icon = "graphics/icons/assembling-machine-2.png", StackSize = 50, Subgroup = "production-machine", Type = "item" },
                        new { Name = "assembling-machine-3", Fluid = false, Icon = "graphics/icons/assembling-machine-3.png", StackSize = 50, Subgroup = "production-machine", Type = "item" },
                        new { Name = "solar-panel", Fluid = false, Icon = "graphics/icons/solar-panel.png", StackSize = 50, Subgroup = "energy", Type = "item" },
                        new { Name = "locomotive", Fluid = false, Icon = "graphics/icons/diesel-locomotive.png", StackSize = 5, Subgroup = "transport", Type = "item-with-entity-data" },
                        new { Name = "cargo-wagon", Fluid = false, Icon = "graphics/icons/cargo-wagon.png", StackSize = 5, Subgroup = "transport", Type = "item-with-entity-data" },
                        new { Name = "fluid-wagon", Fluid = false, Icon = "graphics/icons/fluid-wagon.png", StackSize = 5, Subgroup = "transport", Type = "item-with-entity-data" },
                        new { Name = "artillery-wagon", Fluid = false, Icon = "graphics/icons/artillery-wagon.png", StackSize = 5, Subgroup = "transport", Type = "item-with-entity-data" },
                        new { Name = "rail", Fluid = false, Icon = "graphics/icons/rail.png", StackSize = 100, Subgroup = "transport", Type = "rail-planner" },
                        new { Name = "player-port", Fluid = false, Icon = "graphics/icons/player-port.png", StackSize = 50, Subgroup = "defensive-structure", Type = "item" },
                        new { Name = "gate", Fluid = false, Icon = "graphics/icons/gate.png", StackSize = 50, Subgroup = "defensive-structure", Type = "item" },
                        new { Name = "car", Fluid = false, Icon = "graphics/icons/car.png", StackSize = 1, Subgroup = "transport", Type = "item-with-entity-data" },
                        new { Name = "tank", Fluid = false, Icon = "graphics/icons/tank.png", StackSize = 1, Subgroup = "transport", Type = "item-with-entity-data" },
                        new { Name = "science-pack-1", Fluid = false, Icon = "graphics/icons/science-pack-1.png", StackSize = 200, Subgroup = "science-pack", Type = "tool" },
                        new { Name = "science-pack-2", Fluid = false, Icon = "graphics/icons/science-pack-2.png", StackSize = 200, Subgroup = "science-pack", Type = "tool" },
                        new { Name = "science-pack-3", Fluid = false, Icon = "graphics/icons/science-pack-3.png", StackSize = 200, Subgroup = "science-pack", Type = "tool" },
                        new { Name = "military-science-pack", Fluid = false, Icon = "graphics/icons/military-science-pack.png", StackSize = 200, Subgroup = "science-pack", Type = "tool" },
                        new { Name = "production-science-pack", Fluid = false, Icon = "graphics/icons/production-science-pack.png", StackSize = 200, Subgroup = "science-pack", Type = "tool" },
                        new { Name = "high-tech-science-pack", Fluid = false, Icon = "graphics/icons/high-tech-science-pack.png", StackSize = 200, Subgroup = "science-pack", Type = "tool" },
                        new { Name = "space-science-pack", Fluid = false, Icon = "graphics/icons/space-science-pack.png", StackSize = 2000, Subgroup = "science-pack", Type = "tool" },
                        new { Name = "lab", Fluid = false, Icon = "graphics/icons/lab.png", StackSize = 10, Subgroup = "production-machine", Type = "item" },
                        new { Name = "train-stop", Fluid = false, Icon = "graphics/icons/train-stop.png", StackSize = 10, Subgroup = "transport", Type = "item" },
                        new { Name = "rail-signal", Fluid = false, Icon = "graphics/icons/rail-signal.png", StackSize = 50, Subgroup = "transport", Type = "item" },
                        new { Name = "rail-chain-signal", Fluid = false, Icon = "graphics/icons/rail-chain-signal.png", StackSize = 50, Subgroup = "transport", Type = "item" },
                        new { Name = "steel-plate", Fluid = false, Icon = "graphics/icons/steel-plate.png", StackSize = 100, Subgroup = "raw-material", Type = "item" },
                        new { Name = "underground-belt", Fluid = false, Icon = "graphics/icons/underground-belt.png", StackSize = 50, Subgroup = "belt", Type = "item" },
                        new { Name = "fast-underground-belt", Fluid = false, Icon = "graphics/icons/fast-underground-belt.png", StackSize = 50, Subgroup = "belt", Type = "item" },
                        new { Name = "express-underground-belt", Fluid = false, Icon = "graphics/icons/express-underground-belt.png", StackSize = 50, Subgroup = "belt", Type = "item" },
                        new { Name = "splitter", Fluid = false, Icon = "graphics/icons/splitter.png", StackSize = 50, Subgroup = "belt", Type = "item" },
                        new { Name = "fast-splitter", Fluid = false, Icon = "graphics/icons/fast-splitter.png", StackSize = 50, Subgroup = "belt", Type = "item" },
                        new { Name = "express-splitter", Fluid = false, Icon = "graphics/icons/express-splitter.png", StackSize = 50, Subgroup = "belt", Type = "item" },
                        new { Name = "loader", Fluid = false, Icon = "graphics/icons/loader.png", StackSize = 50, Subgroup = "belt", Type = "item" },
                        new { Name = "fast-loader", Fluid = false, Icon = "graphics/icons/fast-loader.png", StackSize = 50, Subgroup = "belt", Type = "item" },
                        new { Name = "express-loader", Fluid = false, Icon = "graphics/icons/express-loader.png", StackSize = 50, Subgroup = "belt", Type = "item" },
                        new { Name = "advanced-circuit", Fluid = false, Icon = "graphics/icons/advanced-circuit.png", StackSize = 200, Subgroup = "intermediate-product", Type = "item" },
                        new { Name = "processing-unit", Fluid = false, Icon = "graphics/icons/processing-unit.png", StackSize = 100, Subgroup = "intermediate-product", Type = "item" },
                        new { Name = "logistic-robot", Fluid = false, Icon = "graphics/icons/logistic-robot.png", StackSize = 50, Subgroup = "logistic-network", Type = "item" },
                        new { Name = "construction-robot", Fluid = false, Icon = "graphics/icons/construction-robot.png", StackSize = 50, Subgroup = "logistic-network", Type = "item" },
                        new { Name = "logistic-chest-passive-provider", Fluid = false, Icon = "graphics/icons/logistic-chest-passive-provider.png", StackSize = 50, Subgroup = "logistic-network", Type = "item" },
                        new { Name = "logistic-chest-active-provider", Fluid = false, Icon = "graphics/icons/logistic-chest-active-provider.png", StackSize = 50, Subgroup = "logistic-network", Type = "item" },
                        new { Name = "logistic-chest-storage", Fluid = false, Icon = "graphics/icons/logistic-chest-storage.png", StackSize = 50, Subgroup = "logistic-network", Type = "item" },
                        new { Name = "logistic-chest-buffer", Fluid = false, Icon = "graphics/icons/logistic-chest-buffer.png", StackSize = 50, Subgroup = "logistic-network", Type = "item" },
                        new { Name = "logistic-chest-requester", Fluid = false, Icon = "graphics/icons/logistic-chest-requester.png", StackSize = 50, Subgroup = "logistic-network", Type = "item" },
                        new { Name = "rocket-silo", Fluid = false, Icon = "graphics/icons/rocket-silo.png", StackSize = 1, Subgroup = "defensive-structure", Type = "item" },
                        new { Name = "roboport", Fluid = false, Icon = "graphics/icons/roboport.png", StackSize = 10, Subgroup = "logistic-network", Type = "item" },
                        new { Name = "coin", Fluid = false, Icon = "graphics/icons/coin.png", StackSize = 100000, Subgroup = "science-pack", Type = "item" },
                        new { Name = "big-electric-pole", Fluid = false, Icon = "graphics/icons/big-electric-pole.png", StackSize = 50, Subgroup = "energy-pipe-distribution", Type = "item" },
                        new { Name = "medium-electric-pole", Fluid = false, Icon = "graphics/icons/medium-electric-pole.png", StackSize = 50, Subgroup = "energy-pipe-distribution", Type = "item" },
                        new { Name = "substation", Fluid = false, Icon = "graphics/icons/substation.png", StackSize = 50, Subgroup = "energy-pipe-distribution", Type = "item" },
                        new { Name = "accumulator", Fluid = false, Icon = "graphics/icons/accumulator.png", StackSize = 50, Subgroup = "energy", Type = "item" },
                        new { Name = "steel-furnace", Fluid = false, Icon = "graphics/icons/steel-furnace.png", StackSize = 50, Subgroup = "smelting-machine", Type = "item" },
                        new { Name = "electric-furnace", Fluid = false, Icon = "graphics/icons/electric-furnace.png", StackSize = 50, Subgroup = "smelting-machine", Type = "item" },
                        new { Name = "beacon", Fluid = false, Icon = "graphics/icons/beacon.png", StackSize = 10, Subgroup = "module", Type = "item" },
                        new { Name = "storage-tank", Fluid = false, Icon = "graphics/icons/storage-tank.png", StackSize = 50, Subgroup = "storage", Type = "item" },
                        new { Name = "pump", Fluid = false, Icon = "graphics/icons/pump.png", StackSize = 50, Subgroup = "energy-pipe-distribution", Type = "item" },
                        new { Name = "pumpjack", Fluid = false, Icon = "graphics/icons/pumpjack.png", StackSize = 20, Subgroup = "extraction-machine", Type = "item" },
                        new { Name = "oil-refinery", Fluid = false, Icon = "graphics/icons/oil-refinery.png", StackSize = 10, Subgroup = "production-machine", Type = "item" },
                        new { Name = "chemical-plant", Fluid = false, Icon = "graphics/icons/chemical-plant.png", StackSize = 10, Subgroup = "production-machine", Type = "item" },
                        new { Name = "sulfur", Fluid = false, Icon = "graphics/icons/sulfur.png", StackSize = 50, Subgroup = "raw-material", Type = "item" },
                        new { Name = "empty-barrel", Fluid = false, Icon = "graphics/icons/fluid/barreling/empty-barrel.png", StackSize = 10, Subgroup = "intermediate-product", Type = "item" },
                        new { Name = "solid-fuel", Fluid = false, Icon = "graphics/icons/solid-fuel.png", StackSize = 50, Subgroup = "raw-material", Type = "item" },
                        new { Name = "plastic-bar", Fluid = false, Icon = "graphics/icons/plastic-bar.png", StackSize = 100, Subgroup = "raw-material", Type = "item" },
                        new { Name = "engine-unit", Fluid = false, Icon = "graphics/icons/engine-unit.png", StackSize = 50, Subgroup = "intermediate-product", Type = "item" },
                        new { Name = "electric-engine-unit", Fluid = false, Icon = "graphics/icons/electric-engine-unit.png", StackSize = 50, Subgroup = "intermediate-product", Type = "item" },
                        new { Name = "explosives", Fluid = false, Icon = "graphics/icons/explosives.png", StackSize = 50, Subgroup = "raw-material", Type = "item" },
                        new { Name = "battery", Fluid = false, Icon = "graphics/icons/battery.png", StackSize = 200, Subgroup = "raw-material", Type = "item" },
                        new { Name = "flying-robot-frame", Fluid = false, Icon = "graphics/icons/flying-robot-frame.png", StackSize = 50, Subgroup = "intermediate-product", Type = "item" },
                        new { Name = "arithmetic-combinator", Fluid = false, Icon = "graphics/icons/arithmetic-combinator.png", StackSize = 50, Subgroup = "circuit-network", Type = "item" },
                        new { Name = "decider-combinator", Fluid = false, Icon = "graphics/icons/decider-combinator.png", StackSize = 50, Subgroup = "circuit-network", Type = "item" },
                        new { Name = "constant-combinator", Fluid = false, Icon = "graphics/icons/constant-combinator.png", StackSize = 50, Subgroup = "circuit-network", Type = "item" },
                        new { Name = "power-switch", Fluid = false, Icon = "graphics/icons/power-switch.png", StackSize = 50, Subgroup = "circuit-network", Type = "item" },
                        new { Name = "programmable-speaker", Fluid = false, Icon = "graphics/icons/programmable-speaker.png", StackSize = 50, Subgroup = "circuit-network", Type = "item" },
                        new { Name = "low-density-structure", Fluid = false, Icon = "graphics/icons/rocket-structure.png", StackSize = 10, Subgroup = "intermediate-product", Type = "item" },
                        new { Name = "rocket-fuel", Fluid = false, Icon = "graphics/icons/rocket-fuel.png", StackSize = 10, Subgroup = "intermediate-product", Type = "item" },
                        new { Name = "nuclear-fuel", Fluid = false, Icon = "graphics/icons/nuclear-fuel.png", StackSize = 1, Subgroup = "intermediate-product", Type = "item" },
                        new { Name = "rocket-control-unit", Fluid = false, Icon = "graphics/icons/rocket-control-unit.png", StackSize = 10, Subgroup = "intermediate-product", Type = "item" },
                        new { Name = "rocket-part", Fluid = false, Icon = "graphics/icons/rocket-part.png", StackSize = 5, Subgroup = "intermediate-product", Type = "item" },
                        new { Name = "satellite", Fluid = false, Icon = "graphics/icons/satellite.png", StackSize = 1, Subgroup = "intermediate-product", Type = "item" },
                        new { Name = "concrete", Fluid = false, Icon = "graphics/icons/concrete.png", StackSize = 100, Subgroup = "terrain", Type = "item" },
                        new { Name = "refined-concrete", Fluid = false, Icon = "graphics/icons/refined-concrete.png", StackSize = 100, Subgroup = "terrain", Type = "item" },
                        new { Name = "hazard-concrete", Fluid = false, Icon = "graphics/icons/hazard-concrete.png", StackSize = 100, Subgroup = "terrain", Type = "item" },
                        new { Name = "refined-hazard-concrete", Fluid = false, Icon = "graphics/icons/refined-hazard-concrete.png", StackSize = 100, Subgroup = "terrain", Type = "item" },
                        new { Name = "landfill", Fluid = false, Icon = "graphics/icons/landfill.png", StackSize = 100, Subgroup = "terrain", Type = "item" },
                        new { Name = "electric-energy-interface", Fluid = false, Icon = "graphics/icons/accumulator.png", StackSize = 50, Subgroup = "energy", Type = "item" },
                        new { Name = "uranium-ore", Fluid = false, Icon = "graphics/icons/uranium-ore.png", StackSize = 50, Subgroup = "raw-resource", Type = "item" },
                        new { Name = "nuclear-reactor", Fluid = false, Icon = "graphics/icons/nuclear-reactor.png", StackSize = 10, Subgroup = "energy", Type = "item" },
                        new { Name = "uranium-235", Fluid = false, Icon = "graphics/icons/uranium-235.png", StackSize = 100, Subgroup = "intermediate-product", Type = "item" },
                        new { Name = "uranium-238", Fluid = false, Icon = "graphics/icons/uranium-238.png", StackSize = 100, Subgroup = "intermediate-product", Type = "item" },
                        new { Name = "centrifuge", Fluid = false, Icon = "graphics/icons/centrifuge.png", StackSize = 50, Subgroup = "production-machine", Type = "item" },
                        new { Name = "uranium-fuel-cell", Fluid = false, Icon = "graphics/icons/uranium-fuel-cell.png", StackSize = 50, Subgroup = "intermediate-product", Type = "item" },
                        new { Name = "used-up-uranium-fuel-cell", Fluid = false, Icon = "graphics/icons/used-up-uranium-fuel-cell.png", StackSize = 50, Subgroup = "intermediate-product", Type = "item" },
                        new { Name = "heat-exchanger", Fluid = false, Icon = "graphics/icons/heat-boiler.png", StackSize = 50, Subgroup = "energy", Type = "item" },
                        new { Name = "steam-turbine", Fluid = false, Icon = "graphics/icons/steam-turbine.png", StackSize = 10, Subgroup = "energy", Type = "item" },
                        new { Name = "heat-pipe", Fluid = false, Icon = "graphics/icons/heat-pipe.png", StackSize = 50, Subgroup = "energy", Type = "item" },
                        new { Name = "simple-entity-with-force", Fluid = false, Icon = "graphics/icons/steel-chest.png", StackSize = 50, Subgroup = "other", Type = "item" },
                        new { Name = "simple-entity-with-owner", Fluid = false, Icon = "graphics/icons/wooden-chest.png", StackSize = 50, Subgroup = "other", Type = "item" },
                        new { Name = "item-with-tags", Fluid = false, Icon = "graphics/icons/wooden-chest.png", StackSize = 1, Subgroup = "other", Type = "item-with-tags" },
                        new { Name = "item-with-label", Fluid = false, Icon = "graphics/icons/wooden-chest.png", StackSize = 1, Subgroup = "other", Type = "item-with-label" },
                        new { Name = "item-with-inventory", Fluid = false, Icon = "graphics/icons/wooden-chest.png", StackSize = 1, Subgroup = "other", Type = "item-with-inventory" },
                        new { Name = "infinity-chest", Fluid = false, Icon = "graphics/icons/infinity-chest.png", StackSize = 10, Subgroup = "other", Type = "item" },
                        new { Name = "speed-module", Fluid = false, Icon = "graphics/icons/speed-module.png", StackSize = 50, Subgroup = "module", Type = "module" },
                        new { Name = "speed-module-2", Fluid = false, Icon = "graphics/icons/speed-module-2.png", StackSize = 50, Subgroup = "module", Type = "module" },
                        new { Name = "speed-module-3", Fluid = false, Icon = "graphics/icons/speed-module-3.png", StackSize = 50, Subgroup = "module", Type = "module" },
                        new { Name = "effectivity-module", Fluid = false, Icon = "graphics/icons/effectivity-module.png", StackSize = 50, Subgroup = "module", Type = "module" },
                        new { Name = "effectivity-module-2", Fluid = false, Icon = "graphics/icons/effectivity-module-2.png", StackSize = 50, Subgroup = "module", Type = "module" },
                        new { Name = "effectivity-module-3", Fluid = false, Icon = "graphics/icons/effectivity-module-3.png", StackSize = 50, Subgroup = "module", Type = "module" },
                        new { Name = "productivity-module", Fluid = false, Icon = "graphics/icons/productivity-module.png", StackSize = 50, Subgroup = "module", Type = "module" },
                        new { Name = "productivity-module-2", Fluid = false, Icon = "graphics/icons/productivity-module-2.png", StackSize = 50, Subgroup = "module", Type = "module" },
                        new { Name = "productivity-module-3", Fluid = false, Icon = "graphics/icons/productivity-module-3.png", StackSize = 50, Subgroup = "module", Type = "module" },
                        new { Name = "firearm-magazine", Fluid = false, Icon = "graphics/icons/firearm-magazine.png", StackSize = 200, Subgroup = "ammo", Type = "ammo" },
                        new { Name = "piercing-rounds-magazine", Fluid = false, Icon = "graphics/icons/piercing-rounds-magazine.png", StackSize = 200, Subgroup = "ammo", Type = "ammo" },
                        new { Name = "uranium-rounds-magazine", Fluid = false, Icon = "graphics/icons/uranium-rounds-magazine.png", StackSize = 200, Subgroup = "ammo", Type = "ammo" },
                        new { Name = "flamethrower-ammo", Fluid = false, Icon = "graphics/icons/flamethrower-ammo.png", StackSize = 100, Subgroup = "ammo", Type = "ammo" },
                        new { Name = "rocket", Fluid = false, Icon = "graphics/icons/rocket.png", StackSize = 200, Subgroup = "ammo", Type = "ammo" },
                        new { Name = "explosive-rocket", Fluid = false, Icon = "graphics/icons/explosive-rocket.png", StackSize = 200, Subgroup = "ammo", Type = "ammo" },
                        new { Name = "atomic-bomb", Fluid = false, Icon = "graphics/icons/atomic-bomb.png", StackSize = 10, Subgroup = "ammo", Type = "ammo" },
                        new { Name = "shotgun-shell", Fluid = false, Icon = "graphics/icons/shotgun-shell.png", StackSize = 200, Subgroup = "ammo", Type = "ammo" },
                        new { Name = "piercing-shotgun-shell", Fluid = false, Icon = "graphics/icons/piercing-shotgun-shell.png", StackSize = 200, Subgroup = "ammo", Type = "ammo" },
                        new { Name = "railgun-dart", Fluid = false, Icon = "graphics/icons/railgun-ammo.png", StackSize = 200, Subgroup = "ammo", Type = "ammo" },
                        new { Name = "cannon-shell", Fluid = false, Icon = "graphics/icons/cannon-shell.png", StackSize = 200, Subgroup = "ammo", Type = "ammo" },
                        new { Name = "explosive-cannon-shell", Fluid = false, Icon = "graphics/icons/explosive-cannon-shell.png", StackSize = 200, Subgroup = "ammo", Type = "ammo" },
                        new { Name = "uranium-cannon-shell", Fluid = false, Icon = "graphics/icons/uranium-cannon-shell.png", StackSize = 200, Subgroup = "ammo", Type = "ammo" },
                        new { Name = "explosive-uranium-cannon-shell", Fluid = false, Icon = "graphics/icons/explosive-uranium-cannon-shell.png", StackSize = 200, Subgroup = "ammo", Type = "ammo" },
                        new { Name = "artillery-shell", Fluid = false, Icon = "graphics/icons/artillery-shell.png", StackSize = 1, Subgroup = "ammo", Type = "ammo" },
                        new { Name = "grenade", Fluid = false, Icon = "graphics/icons/grenade.png", StackSize = 100, Subgroup = "capsule", Type = "capsule" },
                        new { Name = "cluster-grenade", Fluid = false, Icon = "graphics/icons/cluster-grenade.png", StackSize = 100, Subgroup = "capsule", Type = "capsule" },
                        new { Name = "poison-capsule", Fluid = false, Icon = "graphics/icons/poison-capsule.png", StackSize = 100, Subgroup = "capsule", Type = "capsule" },
                        new { Name = "slowdown-capsule", Fluid = false, Icon = "graphics/icons/slowdown-capsule.png", StackSize = 100, Subgroup = "capsule", Type = "capsule" },
                        new { Name = "defender-capsule", Fluid = false, Icon = "graphics/icons/defender.png", StackSize = 100, Subgroup = "capsule", Type = "capsule" },
                        new { Name = "distractor-capsule", Fluid = false, Icon = "graphics/icons/distractor.png", StackSize = 100, Subgroup = "capsule", Type = "capsule" },
                        new { Name = "destroyer-capsule", Fluid = false, Icon = "graphics/icons/destroyer.png", StackSize = 100, Subgroup = "capsule", Type = "capsule" },
                        new { Name = "discharge-defense-remote", Fluid = false, Icon = "graphics/equipment/discharge-defense-equipment-ability.png", StackSize = 1, Subgroup = "capsule", Type = "capsule" },
                        new { Name = "cliff-explosives", Fluid = false, Icon = "graphics/icons/cliff-explosives.png", StackSize = 20, Subgroup = "terrain", Type = "capsule" },
                        new { Name = "artillery-targeting-remote", Fluid = false, Icon = "graphics/icons/artillery-targeting-remote.png", StackSize = 1, Subgroup = "capsule", Type = "capsule" },
                        new { Name = "pistol", Fluid = false, Icon = "graphics/icons/pistol.png", StackSize = 5, Subgroup = "gun", Type = "gun" },
                        new { Name = "submachine-gun", Fluid = false, Icon = "graphics/icons/submachine-gun.png", StackSize = 5, Subgroup = "gun", Type = "gun" },
                        new { Name = "flamethrower", Fluid = false, Icon = "graphics/icons/flamethrower.png", StackSize = 5, Subgroup = "gun", Type = "gun" },
                        new { Name = "vehicle-machine-gun", Fluid = false, Icon = "graphics/icons/submachine-gun.png", StackSize = 1, Subgroup = "gun", Type = "gun" },
                        new { Name = "tank-machine-gun", Fluid = false, Icon = "graphics/icons/submachine-gun.png", StackSize = 1, Subgroup = "gun", Type = "gun" },
                        new { Name = "tank-flamethrower", Fluid = false, Icon = "graphics/icons/flamethrower.png", StackSize = 1, Subgroup = "gun", Type = "gun" },
                        new { Name = "land-mine", Fluid = false, Icon = "graphics/icons/land-mine.png", StackSize = 100, Subgroup = "gun", Type = "item" },
                        new { Name = "rocket-launcher", Fluid = false, Icon = "graphics/icons/rocket-launcher.png", StackSize = 5, Subgroup = "gun", Type = "gun" },
                        new { Name = "shotgun", Fluid = false, Icon = "graphics/icons/shotgun.png", StackSize = 5, Subgroup = "gun", Type = "gun" },
                        new { Name = "combat-shotgun", Fluid = false, Icon = "graphics/icons/combat-shotgun.png", StackSize = 5, Subgroup = "gun", Type = "gun" },
                        new { Name = "railgun", Fluid = false, Icon = "graphics/icons/railgun.png", StackSize = 5, Subgroup = "gun", Type = "gun" },
                        new { Name = "tank-cannon", Fluid = false, Icon = "graphics/icons/tank-cannon.png", StackSize = 0, Subgroup = "gun", Type = "gun" },
                        new { Name = "artillery-wagon-cannon", Fluid = false, Icon = "graphics/icons/tank-cannon.png", StackSize = 0, Subgroup = "gun", Type = "gun" },
                        new { Name = "light-armor", Fluid = false, Icon = "graphics/icons/light-armor.png", StackSize = 10, Subgroup = "armor", Type = "armor" },
                        new { Name = "heavy-armor", Fluid = false, Icon = "graphics/icons/heavy-armor.png", StackSize = 10, Subgroup = "armor", Type = "armor" },
                        new { Name = "modular-armor", Fluid = false, Icon = "graphics/icons/modular-armor.png", StackSize = 1, Subgroup = "armor", Type = "armor" },
                        new { Name = "power-armor", Fluid = false, Icon = "graphics/icons/power-armor.png", StackSize = 1, Subgroup = "armor", Type = "armor" },
                        new { Name = "power-armor-mk2", Fluid = false, Icon = "graphics/icons/power-armor-mk2.png", StackSize = 1, Subgroup = "armor", Type = "armor" },
                        new { Name = "gun-turret", Fluid = false, Icon = "graphics/icons/gun-turret.png", StackSize = 50, Subgroup = "defensive-structure", Type = "item" },
                        new { Name = "laser-turret", Fluid = false, Icon = "graphics/icons/laser-turret.png", StackSize = 50, Subgroup = "defensive-structure", Type = "item" },
                        new { Name = "flamethrower-turret", Fluid = false, Icon = "graphics/icons/flamethrower-turret.png", StackSize = 50, Subgroup = "defensive-structure", Type = "item" },
                        new { Name = "artillery-turret", Fluid = false, Icon = "graphics/icons/artillery-turret.png", StackSize = 10, Subgroup = "defensive-structure", Type = "item" }
                    );
                });

            modelBuilder.Entity("FNO.Domain.Models.FactorioTechnology", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Icon");

                    b.Property<int>("Level");

                    b.Property<string>("MaxLevel");

                    b.Property<bool>("Upgradeable");

                    b.HasKey("Name");

                    b.ToTable("TechnologyLibrary");

                    b.HasData(
                        new { Name = "steel-processing", Icon = "graphics/technology/steel-processing.png", Level = 0, Upgradeable = false },
                        new { Name = "military", Icon = "graphics/technology/military.png", Level = 0, Upgradeable = false },
                        new { Name = "military-2", Icon = "graphics/technology/military.png", Level = 0, Upgradeable = false },
                        new { Name = "military-3", Icon = "graphics/technology/military.png", Level = 0, Upgradeable = false },
                        new { Name = "military-4", Icon = "graphics/technology/military.png", Level = 0, Upgradeable = false },
                        new { Name = "uranium-ammo", Icon = "graphics/technology/uranium-ammo.png", Level = 0, Upgradeable = false },
                        new { Name = "atomic-bomb", Icon = "graphics/technology/atomic-bomb.png", Level = 0, Upgradeable = false },
                        new { Name = "grenade-damage-1", Icon = "graphics/technology/grenade-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "grenade-damage-2", Icon = "graphics/technology/grenade-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "grenade-damage-3", Icon = "graphics/technology/grenade-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "grenade-damage-4", Icon = "graphics/technology/grenade-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "grenade-damage-5", Icon = "graphics/technology/grenade-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "grenade-damage-6", Icon = "graphics/technology/grenade-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "grenade-damage-7", Icon = "graphics/technology/grenade-damage.png", Level = 0, MaxLevel = "infinite", Upgradeable = true },
                        new { Name = "automation", Icon = "graphics/technology/automation.png", Level = 0, Upgradeable = false },
                        new { Name = "electronics", Icon = "graphics/technology/electronics.png", Level = 0, Upgradeable = false },
                        new { Name = "automation-2", Icon = "graphics/technology/automation.png", Level = 0, Upgradeable = false },
                        new { Name = "automation-3", Icon = "graphics/technology/automation.png", Level = 0, Upgradeable = false },
                        new { Name = "explosives", Icon = "graphics/technology/explosives.png", Level = 0, Upgradeable = false },
                        new { Name = "cliff-explosives", Icon = "graphics/technology/cliff-explosives.png", Level = 0, Upgradeable = false },
                        new { Name = "flammables", Icon = "graphics/technology/flammables.png", Level = 0, Upgradeable = false },
                        new { Name = "land-mine", Icon = "graphics/technology/land-mine.png", Level = 0, Upgradeable = false },
                        new { Name = "flamethrower", Icon = "graphics/technology/flamethrower.png", Level = 0, Upgradeable = false },
                        new { Name = "circuit-network", Icon = "graphics/technology/circuit-network.png", Level = 0, Upgradeable = false },
                        new { Name = "advanced-electronics", Icon = "graphics/technology/advanced-electronics.png", Level = 0, Upgradeable = false },
                        new { Name = "advanced-electronics-2", Icon = "graphics/technology/advanced-electronics-2.png", Level = 0, Upgradeable = false },
                        new { Name = "logistics", Icon = "graphics/technology/logistics.png", Level = 0, Upgradeable = false },
                        new { Name = "railway", Icon = "graphics/technology/railway.png", Level = 0, Upgradeable = false },
                        new { Name = "fluid-wagon", Icon = "graphics/technology/fluid-wagon.png", Level = 0, Upgradeable = false },
                        new { Name = "automated-rail-transportation", Icon = "graphics/technology/automated-rail-transportation.png", Level = 0, Upgradeable = false },
                        new { Name = "rail-signals", Icon = "graphics/technology/rail-signals.png", Level = 0, Upgradeable = false },
                        new { Name = "braking-force-1", Icon = "graphics/technology/braking-force.png", Level = 0, Upgradeable = true },
                        new { Name = "braking-force-2", Icon = "graphics/technology/braking-force.png", Level = 0, Upgradeable = true },
                        new { Name = "braking-force-3", Icon = "graphics/technology/braking-force.png", Level = 0, Upgradeable = true },
                        new { Name = "braking-force-4", Icon = "graphics/technology/braking-force.png", Level = 0, Upgradeable = true },
                        new { Name = "braking-force-5", Icon = "graphics/technology/braking-force.png", Level = 0, Upgradeable = true },
                        new { Name = "braking-force-6", Icon = "graphics/technology/braking-force.png", Level = 0, Upgradeable = true },
                        new { Name = "braking-force-7", Icon = "graphics/technology/braking-force.png", Level = 0, Upgradeable = true },
                        new { Name = "automobilism", Icon = "graphics/technology/automobilism.png", Level = 0, Upgradeable = false },
                        new { Name = "tanks", Icon = "graphics/technology/tanks.png", Level = 0, Upgradeable = false },
                        new { Name = "logistics-2", Icon = "graphics/technology/logistics.png", Level = 0, Upgradeable = false },
                        new { Name = "logistics-3", Icon = "graphics/technology/logistics.png", Level = 0, Upgradeable = false },
                        new { Name = "optics", Icon = "graphics/technology/optics.png", Level = 0, Upgradeable = false },
                        new { Name = "solar-energy", Icon = "graphics/technology/solar-energy.png", Level = 0, Upgradeable = false },
                        new { Name = "laser", Icon = "graphics/technology/laser.png", Level = 0, Upgradeable = false },
                        new { Name = "rocketry", Icon = "graphics/technology/rocketry.png", Level = 0, Upgradeable = false },
                        new { Name = "explosive-rocketry", Icon = "graphics/technology/explosive-rocketry.png", Level = 0, Upgradeable = false },
                        new { Name = "heavy-armor", Icon = "graphics/technology/armor-making.png", Level = 0, Upgradeable = false },
                        new { Name = "modular-armor", Icon = "graphics/technology/armor-making.png", Level = 0, Upgradeable = false },
                        new { Name = "power-armor", Icon = "graphics/technology/power-armor.png", Level = 0, Upgradeable = false },
                        new { Name = "power-armor-2", Icon = "graphics/technology/power-armor-mk2.png", Level = 0, Upgradeable = false },
                        new { Name = "turrets", Icon = "graphics/technology/turrets.png", Level = 0, Upgradeable = false },
                        new { Name = "laser-turrets", Icon = "graphics/technology/laser-turrets.png", Level = 0, Upgradeable = false },
                        new { Name = "stone-walls", Icon = "graphics/technology/stone-walls.png", Level = 0, Upgradeable = false },
                        new { Name = "gates", Icon = "graphics/technology/gates.png", Level = 0, Upgradeable = false },
                        new { Name = "flying", Icon = "graphics/technology/flying.png", Level = 0, Upgradeable = false },
                        new { Name = "robotics", Icon = "graphics/technology/robotics.png", Level = 0, Upgradeable = false },
                        new { Name = "rocket-silo", Icon = "graphics/technology/rocket-silo.png", Level = 0, Upgradeable = false },
                        new { Name = "research-speed-1", Icon = "graphics/technology/research-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "research-speed-2", Icon = "graphics/technology/research-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "research-speed-3", Icon = "graphics/technology/research-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "research-speed-4", Icon = "graphics/technology/research-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "research-speed-5", Icon = "graphics/technology/research-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "research-speed-6", Icon = "graphics/technology/research-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "electric-energy-distribution-1", Icon = "graphics/technology/electric-energy-distribution.png", Level = 0, Upgradeable = false },
                        new { Name = "electric-energy-distribution-2", Icon = "graphics/technology/electric-energy-distribution.png", Level = 0, Upgradeable = false },
                        new { Name = "electric-energy-accumulators-1", Icon = "graphics/technology/electric-energy-acumulators.png", Level = 0, Upgradeable = false },
                        new { Name = "advanced-material-processing", Icon = "graphics/technology/advanced-material-processing.png", Level = 0, Upgradeable = false },
                        new { Name = "advanced-material-processing-2", Icon = "graphics/technology/advanced-material-processing.png", Level = 0, Upgradeable = false },
                        new { Name = "concrete", Icon = "graphics/technology/concrete.png", Level = 0, Upgradeable = false },
                        new { Name = "effect-transmission", Icon = "graphics/technology/effect-transmission.png", Level = 0, Upgradeable = false },
                        new { Name = "toolbelt", Icon = "graphics/technology/toolbelt.png", Level = 0, Upgradeable = false },
                        new { Name = "engine", Icon = "graphics/technology/engine.png", Level = 0, Upgradeable = false },
                        new { Name = "electric-engine", Icon = "graphics/technology/electric-engine.png", Level = 0, Upgradeable = false },
                        new { Name = "battery", Icon = "graphics/technology/battery.png", Level = 0, Upgradeable = false },
                        new { Name = "landfill", Icon = "graphics/technology/landfill.png", Level = 0, Upgradeable = false },
                        new { Name = "construction-robotics", Icon = "graphics/technology/construction-robotics.png", Level = 0, Upgradeable = false },
                        new { Name = "logistic-robotics", Icon = "graphics/technology/logistic-robotics.png", Level = 0, Upgradeable = false },
                        new { Name = "logistic-system", Icon = "graphics/technology/logistic-system.png", Level = 0, Upgradeable = false },
                        new { Name = "worker-robots-speed-1", Icon = "graphics/technology/worker-robots-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "worker-robots-speed-2", Icon = "graphics/technology/worker-robots-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "worker-robots-speed-3", Icon = "graphics/technology/worker-robots-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "worker-robots-speed-4", Icon = "graphics/technology/worker-robots-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "worker-robots-speed-5", Icon = "graphics/technology/worker-robots-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "worker-robots-speed-6", Icon = "graphics/technology/worker-robots-speed.png", Level = 0, MaxLevel = "infinite", Upgradeable = true },
                        new { Name = "worker-robots-storage-1", Icon = "graphics/technology/worker-robots-storage.png", Level = 0, Upgradeable = true },
                        new { Name = "worker-robots-storage-2", Icon = "graphics/technology/worker-robots-storage.png", Level = 0, Upgradeable = true },
                        new { Name = "worker-robots-storage-3", Icon = "graphics/technology/worker-robots-storage.png", Level = 0, Upgradeable = true },
                        new { Name = "character-logistic-slots-1", Icon = "graphics/technology/character-logistic-slots.png", Level = 0, Upgradeable = true },
                        new { Name = "character-logistic-slots-2", Icon = "graphics/technology/character-logistic-slots.png", Level = 0, Upgradeable = true },
                        new { Name = "character-logistic-slots-3", Icon = "graphics/technology/character-logistic-slots.png", Level = 0, Upgradeable = true },
                        new { Name = "character-logistic-slots-4", Icon = "graphics/technology/character-logistic-slots.png", Level = 0, Upgradeable = true },
                        new { Name = "character-logistic-slots-5", Icon = "graphics/technology/character-logistic-slots.png", Level = 0, Upgradeable = true },
                        new { Name = "character-logistic-slots-6", Icon = "graphics/technology/character-logistic-slots.png", Level = 0, Upgradeable = true },
                        new { Name = "character-logistic-trash-slots-1", Icon = "graphics/technology/character-logistic-trash-slots.png", Level = 0, Upgradeable = true },
                        new { Name = "character-logistic-trash-slots-2", Icon = "graphics/technology/character-logistic-trash-slots.png", Level = 0, Upgradeable = true },
                        new { Name = "auto-character-logistic-trash-slots", Icon = "graphics/technology/character-auto-logistic-trash-slots.png", Level = 0, Upgradeable = false },
                        new { Name = "shotgun-shell-damage-1", Icon = "graphics/technology/shotgun-shell-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "shotgun-shell-damage-2", Icon = "graphics/technology/shotgun-shell-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "shotgun-shell-damage-3", Icon = "graphics/technology/shotgun-shell-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "shotgun-shell-damage-4", Icon = "graphics/technology/shotgun-shell-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "shotgun-shell-damage-5", Icon = "graphics/technology/shotgun-shell-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "shotgun-shell-damage-6", Icon = "graphics/technology/shotgun-shell-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "shotgun-shell-damage-7", Icon = "graphics/technology/shotgun-shell-damage.png", Level = 0, MaxLevel = "infinite", Upgradeable = true },
                        new { Name = "shotgun-shell-speed-1", Icon = "graphics/technology/shotgun-shell-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "shotgun-shell-speed-2", Icon = "graphics/technology/shotgun-shell-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "shotgun-shell-speed-3", Icon = "graphics/technology/shotgun-shell-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "shotgun-shell-speed-4", Icon = "graphics/technology/shotgun-shell-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "shotgun-shell-speed-5", Icon = "graphics/technology/shotgun-shell-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "shotgun-shell-speed-6", Icon = "graphics/technology/shotgun-shell-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "laser-turret-damage-1", Icon = "graphics/technology/laser-turret-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "laser-turret-damage-2", Icon = "graphics/technology/laser-turret-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "laser-turret-damage-3", Icon = "graphics/technology/laser-turret-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "laser-turret-damage-4", Icon = "graphics/technology/laser-turret-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "laser-turret-damage-5", Icon = "graphics/technology/laser-turret-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "laser-turret-damage-6", Icon = "graphics/technology/laser-turret-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "laser-turret-damage-7", Icon = "graphics/technology/laser-turret-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "laser-turret-damage-8", Icon = "graphics/technology/laser-turret-damage.png", Level = 0, MaxLevel = "infinite", Upgradeable = true },
                        new { Name = "laser-turret-speed-1", Icon = "graphics/technology/laser-turret-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "laser-turret-speed-2", Icon = "graphics/technology/laser-turret-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "laser-turret-speed-3", Icon = "graphics/technology/laser-turret-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "laser-turret-speed-4", Icon = "graphics/technology/laser-turret-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "laser-turret-speed-5", Icon = "graphics/technology/laser-turret-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "laser-turret-speed-6", Icon = "graphics/technology/laser-turret-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "laser-turret-speed-7", Icon = "graphics/technology/laser-turret-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "gun-turret-damage-1", Icon = "graphics/technology/gun-turret-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "gun-turret-damage-2", Icon = "graphics/technology/gun-turret-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "gun-turret-damage-3", Icon = "graphics/technology/gun-turret-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "gun-turret-damage-4", Icon = "graphics/technology/gun-turret-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "gun-turret-damage-5", Icon = "graphics/technology/gun-turret-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "gun-turret-damage-6", Icon = "graphics/technology/gun-turret-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "gun-turret-damage-7", Icon = "graphics/technology/gun-turret-damage.png", Level = 0, MaxLevel = "infinite", Upgradeable = true },
                        new { Name = "flamethrower-damage-1", Icon = "graphics/technology/flamethrower-turret-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "flamethrower-damage-2", Icon = "graphics/technology/flamethrower-turret-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "flamethrower-damage-3", Icon = "graphics/technology/flamethrower-turret-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "flamethrower-damage-4", Icon = "graphics/technology/flamethrower-turret-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "flamethrower-damage-5", Icon = "graphics/technology/flamethrower-turret-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "flamethrower-damage-6", Icon = "graphics/technology/flamethrower-turret-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "flamethrower-damage-7", Icon = "graphics/technology/flamethrower-turret-damage.png", Level = 0, MaxLevel = "infinite", Upgradeable = true },
                        new { Name = "energy-shield-equipment", Icon = "graphics/technology/energy-shield-equipment.png", Level = 0, Upgradeable = false },
                        new { Name = "night-vision-equipment", Icon = "graphics/technology/night-vision-equipment.png", Level = 0, Upgradeable = false },
                        new { Name = "energy-shield-mk2-equipment", Icon = "graphics/technology/energy-shield-mk2-equipment.png", Level = 0, Upgradeable = false },
                        new { Name = "battery-equipment", Icon = "graphics/technology/battery-equipment.png", Level = 0, Upgradeable = false },
                        new { Name = "battery-mk2-equipment", Icon = "graphics/technology/battery-mk2-equipment.png", Level = 0, Upgradeable = false },
                        new { Name = "solar-panel-equipment", Icon = "graphics/technology/solar-panel-equipment.png", Level = 0, Upgradeable = false },
                        new { Name = "personal-laser-defense-equipment", Icon = "graphics/technology/personal-laser-defense-equipment.png", Level = 0, Upgradeable = false },
                        new { Name = "discharge-defense-equipment", Icon = "graphics/technology/discharge-defense-equipment.png", Level = 0, Upgradeable = false },
                        new { Name = "fusion-reactor-equipment", Icon = "graphics/technology/fusion-reactor-equipment.png", Level = 0, Upgradeable = false },
                        new { Name = "exoskeleton-equipment", Icon = "graphics/technology/exoskeleton-equipment.png", Level = 0, Upgradeable = false },
                        new { Name = "personal-roboport-equipment", Icon = "graphics/technology/personal-roboport-equipment.png", Level = 0, Upgradeable = false },
                        new { Name = "personal-roboport-equipment-2", Icon = "graphics/technology/personal-roboport-equipment.png", Level = 0, Upgradeable = false },
                        new { Name = "bullet-damage-1", Icon = "graphics/technology/bullet-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "bullet-damage-2", Icon = "graphics/technology/bullet-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "bullet-damage-3", Icon = "graphics/technology/bullet-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "bullet-damage-4", Icon = "graphics/technology/bullet-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "bullet-damage-5", Icon = "graphics/technology/bullet-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "bullet-damage-6", Icon = "graphics/technology/bullet-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "bullet-damage-7", Icon = "graphics/technology/bullet-damage.png", Level = 0, MaxLevel = "infinite", Upgradeable = true },
                        new { Name = "bullet-speed-1", Icon = "graphics/technology/bullet-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "bullet-speed-2", Icon = "graphics/technology/bullet-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "bullet-speed-3", Icon = "graphics/technology/bullet-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "bullet-speed-4", Icon = "graphics/technology/bullet-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "bullet-speed-5", Icon = "graphics/technology/bullet-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "bullet-speed-6", Icon = "graphics/technology/bullet-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "fluid-handling", Icon = "graphics/technology/fluid-handling.png", Level = 0, Upgradeable = false },
                        new { Name = "oil-processing", Icon = "graphics/technology/oil-gathering.png", Level = 0, Upgradeable = false },
                        new { Name = "advanced-oil-processing", Icon = "graphics/technology/oil-processing.png", Level = 0, Upgradeable = false },
                        new { Name = "coal-liquefaction", Icon = "graphics/technology/coal-liquefaction.png", Level = 0, Upgradeable = false },
                        new { Name = "sulfur-processing", Icon = "graphics/technology/sulfur-processing.png", Level = 0, Upgradeable = false },
                        new { Name = "plastics", Icon = "graphics/technology/plastics.png", Level = 0, Upgradeable = false },
                        new { Name = "modules", Icon = "graphics/technology/module.png", Level = 0, Upgradeable = false },
                        new { Name = "speed-module", Icon = "graphics/technology/speed-module.png", Level = 0, Upgradeable = true },
                        new { Name = "speed-module-2", Icon = "graphics/technology/speed-module.png", Level = 0, Upgradeable = true },
                        new { Name = "speed-module-3", Icon = "graphics/technology/speed-module.png", Level = 0, Upgradeable = true },
                        new { Name = "productivity-module", Icon = "graphics/technology/productivity-module.png", Level = 0, Upgradeable = true },
                        new { Name = "productivity-module-2", Icon = "graphics/technology/productivity-module.png", Level = 0, Upgradeable = true },
                        new { Name = "productivity-module-3", Icon = "graphics/technology/productivity-module.png", Level = 0, Upgradeable = true },
                        new { Name = "effectivity-module", Icon = "graphics/technology/effectivity-module.png", Level = 0, Upgradeable = true },
                        new { Name = "effectivity-module-2", Icon = "graphics/technology/effectivity-module.png", Level = 0, Upgradeable = true },
                        new { Name = "effectivity-module-3", Icon = "graphics/technology/effectivity-module.png", Level = 0, Upgradeable = true },
                        new { Name = "combat-robotics", Icon = "graphics/technology/combat-robotics.png", Level = 0, Upgradeable = false },
                        new { Name = "combat-robotics-2", Icon = "graphics/technology/combat-robotics.png", Level = 0, Upgradeable = false },
                        new { Name = "combat-robotics-3", Icon = "graphics/technology/combat-robotics.png", Level = 0, Upgradeable = false },
                        new { Name = "combat-robot-damage-1", Icon = "graphics/technology/combat-robot-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "combat-robot-damage-2", Icon = "graphics/technology/combat-robot-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "combat-robot-damage-3", Icon = "graphics/technology/combat-robot-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "combat-robot-damage-4", Icon = "graphics/technology/combat-robot-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "combat-robot-damage-5", Icon = "graphics/technology/combat-robot-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "combat-robot-damage-6", Icon = "graphics/technology/combat-robot-damage.png", Level = 0, MaxLevel = "infinite", Upgradeable = true },
                        new { Name = "rocket-damage-1", Icon = "graphics/technology/rocket-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "rocket-damage-2", Icon = "graphics/technology/rocket-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "rocket-damage-3", Icon = "graphics/technology/rocket-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "rocket-damage-4", Icon = "graphics/technology/rocket-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "rocket-damage-5", Icon = "graphics/technology/rocket-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "rocket-damage-6", Icon = "graphics/technology/rocket-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "rocket-damage-7", Icon = "graphics/technology/rocket-damage.png", Level = 0, MaxLevel = "infinite", Upgradeable = true },
                        new { Name = "rocket-speed-1", Icon = "graphics/technology/rocket-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "rocket-speed-2", Icon = "graphics/technology/rocket-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "rocket-speed-3", Icon = "graphics/technology/rocket-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "rocket-speed-4", Icon = "graphics/technology/rocket-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "rocket-speed-5", Icon = "graphics/technology/rocket-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "rocket-speed-6", Icon = "graphics/technology/rocket-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "rocket-speed-7", Icon = "graphics/technology/rocket-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "cannon-shell-damage-1", Icon = "graphics/technology/cannon-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "cannon-shell-damage-2", Icon = "graphics/technology/cannon-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "cannon-shell-damage-3", Icon = "graphics/technology/cannon-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "cannon-shell-damage-4", Icon = "graphics/technology/cannon-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "cannon-shell-damage-5", Icon = "graphics/technology/cannon-damage.png", Level = 0, Upgradeable = true },
                        new { Name = "cannon-shell-damage-6", Icon = "graphics/technology/cannon-damage.png", Level = 0, MaxLevel = "infinite", Upgradeable = true },
                        new { Name = "cannon-shell-speed-1", Icon = "graphics/technology/cannon-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "cannon-shell-speed-2", Icon = "graphics/technology/cannon-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "cannon-shell-speed-3", Icon = "graphics/technology/cannon-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "cannon-shell-speed-4", Icon = "graphics/technology/cannon-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "cannon-shell-speed-5", Icon = "graphics/technology/cannon-speed.png", Level = 0, Upgradeable = true },
                        new { Name = "artillery-shell-range-1", Icon = "graphics/technology/artillery-range.png", Level = 0, MaxLevel = "infinite", Upgradeable = false },
                        new { Name = "artillery-shell-speed-1", Icon = "graphics/technology/artillery-speed.png", Level = 0, MaxLevel = "infinite", Upgradeable = false },
                        new { Name = "follower-robot-count-1", Icon = "graphics/technology/follower-robots.png", Level = 0, Upgradeable = true },
                        new { Name = "follower-robot-count-2", Icon = "graphics/technology/follower-robots.png", Level = 0, Upgradeable = true },
                        new { Name = "follower-robot-count-3", Icon = "graphics/technology/follower-robots.png", Level = 0, Upgradeable = true },
                        new { Name = "follower-robot-count-4", Icon = "graphics/technology/follower-robots.png", Level = 0, Upgradeable = true },
                        new { Name = "follower-robot-count-5", Icon = "graphics/technology/follower-robots.png", Level = 0, Upgradeable = true },
                        new { Name = "follower-robot-count-6", Icon = "graphics/technology/follower-robots.png", Level = 0, Upgradeable = true },
                        new { Name = "follower-robot-count-7", Icon = "graphics/technology/follower-robots.png", Level = 14, MaxLevel = "infinite", Upgradeable = true },
                        new { Name = "nuclear-power", Icon = "graphics/technology/nuclear-power.png", Level = 0, Upgradeable = false },
                        new { Name = "kovarex-enrichment-process", Icon = "graphics/technology/kovarex-enrichment-process.png", Level = 0, Upgradeable = false },
                        new { Name = "nuclear-fuel-reprocessing", Icon = "graphics/technology/nuclear-fuel-reprocessing.png", Level = 0, Upgradeable = false },
                        new { Name = "mining-productivity-1", Icon = "graphics/technology/mining-productivity.png", Level = 0, MaxLevel = "3", Upgradeable = true },
                        new { Name = "mining-productivity-4", Icon = "graphics/technology/mining-productivity.png", Level = 0, MaxLevel = "7", Upgradeable = true },
                        new { Name = "mining-productivity-8", Icon = "graphics/technology/mining-productivity.png", Level = 0, MaxLevel = "11", Upgradeable = true },
                        new { Name = "mining-productivity-12", Icon = "graphics/technology/mining-productivity.png", Level = 0, MaxLevel = "15", Upgradeable = true },
                        new { Name = "mining-productivity-16", Icon = "graphics/technology/mining-productivity.png", Level = 0, MaxLevel = "infinite", Upgradeable = true },
                        new { Name = "artillery", Icon = "graphics/technology/artillery.png", Level = 0, Upgradeable = false },
                        new { Name = "stack-inserter", Icon = "graphics/technology/stack-inserter.png", Level = 0, Upgradeable = true },
                        new { Name = "inserter-capacity-bonus-1", Icon = "graphics/technology/inserter-capacity.png", Level = 0, Upgradeable = true },
                        new { Name = "inserter-capacity-bonus-2", Icon = "graphics/technology/inserter-capacity.png", Level = 0, Upgradeable = true },
                        new { Name = "inserter-capacity-bonus-3", Icon = "graphics/technology/inserter-capacity.png", Level = 0, Upgradeable = true },
                        new { Name = "inserter-capacity-bonus-4", Icon = "graphics/technology/inserter-capacity.png", Level = 0, Upgradeable = true },
                        new { Name = "inserter-capacity-bonus-5", Icon = "graphics/technology/inserter-capacity.png", Level = 0, Upgradeable = true },
                        new { Name = "inserter-capacity-bonus-6", Icon = "graphics/technology/inserter-capacity.png", Level = 0, Upgradeable = true },
                        new { Name = "inserter-capacity-bonus-7", Icon = "graphics/technology/inserter-capacity.png", Level = 0, Upgradeable = true }
                    );
                });

            modelBuilder.Entity("FNO.Domain.Models.Factory", b =>
                {
                    b.Property<Guid>("FactoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CorporationId");

                    b.Property<string>("CurrentlyResearchingId");

                    b.Property<long>("LastSeen");

                    b.Property<int>("PlayersOnline");

                    b.Property<int>("Port");

                    b.HasKey("FactoryId");

                    b.HasIndex("CorporationId");

                    b.HasIndex("CurrentlyResearchingId");

                    b.ToTable("Factories");
                });

            modelBuilder.Entity("FNO.Domain.Models.Player", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CorporationId");

                    b.HasKey("PlayerId");

                    b.HasIndex("CorporationId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("FNO.Domain.Models.Warehouse", b =>
                {
                    b.Property<Guid>("WarehouseId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CorporationId");

                    b.HasKey("WarehouseId");

                    b.HasIndex("CorporationId")
                        .IsUnique();

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("FNO.Domain.Models.WarehouseInventory", b =>
                {
                    b.Property<Guid>("WarehouseInventoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("FactorioEntityId");

                    b.Property<string>("FactorioEntityName");

                    b.Property<int>("Quantity");

                    b.Property<Guid>("WarehouseId");

                    b.HasKey("WarehouseInventoryId");

                    b.HasIndex("FactorioEntityName");

                    b.HasIndex("WarehouseId");

                    b.ToTable("WarehouseInventories");
                });

            modelBuilder.Entity("FNO.Domain.Models.Factory", b =>
                {
                    b.HasOne("FNO.Domain.Models.Corporation", "Corporation")
                        .WithMany()
                        .HasForeignKey("CorporationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FNO.Domain.Models.FactorioTechnology", "CurrentlyResearching")
                        .WithMany()
                        .HasForeignKey("CurrentlyResearchingId");
                });

            modelBuilder.Entity("FNO.Domain.Models.Player", b =>
                {
                    b.HasOne("FNO.Domain.Models.Corporation", "Corporation")
                        .WithMany("Members")
                        .HasForeignKey("CorporationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FNO.Domain.Models.Warehouse", b =>
                {
                    b.HasOne("FNO.Domain.Models.Corporation", "Corporation")
                        .WithOne("Warehouse")
                        .HasForeignKey("FNO.Domain.Models.Warehouse", "CorporationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FNO.Domain.Models.WarehouseInventory", b =>
                {
                    b.HasOne("FNO.Domain.Models.FactorioEntity", "FactorioEntity")
                        .WithMany()
                        .HasForeignKey("FactorioEntityName");

                    b.HasOne("FNO.Domain.Models.Warehouse", "Warehouse")
                        .WithMany("Inventory")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
